/**
 * Head & Neck Region Seed Data
 * Comprehensive anatomical structures, systems, and relationships
 * Based on Netter's Atlas of Human Anatomy plates 1-148
 */

import { StructureType, RelationshipType } from '@/types';

// ============================================================================
// Seed Data Interface
// ============================================================================

export interface HeadNeckSeedData {
  region: {
    name: string;
    slug: string;
    description: string;
    atlas_plate_range: string;
    sort_order: number;
    thumbnail_url: string;
    color_code: string;
  };
  systems: Array<{
    name: string;
    slug: string;
    description: string;
    color_code: string;
  }>;
  structures: Array<{
    canonical_name: string;
    common_names: string[];
    latin_name: string | null;
    pronunciation_ipa: string;
    system_slugs: string[];
    structure_type: StructureType;
    parent_structure_name: string | null;
    definition_brief: string;
    description_full: string;
    clinical_significance: string;
    origin: string | null;
    insertion: string | null;
    action: string | null;
    innervation: string | null;
    blood_supply: string | null;
    model_reference: string;
    difficulty_rating: number;
    prerequisite_names: string[];
  }>;
  relationships: Array<{
    source_structure_name: string;
    target_structure_name: string;
    relationship_type: RelationshipType;
    description: string;
    bidirectional: boolean;
    clinical_relevance: string | null;
  }>;
}

// ============================================================================
// Region Definition
// ============================================================================

const region = {
  name: 'Head & Neck',
  slug: 'head-neck',
  description: 'Cranium, face, neck structures including brain, special senses, and cervical anatomy',
  atlas_plate_range: '1-148',
  sort_order: 1,
  thumbnail_url: '/assets/regions/head-neck.png',
  color_code: '#8B5CF6', // Purple for neural/cranial emphasis
};

// ============================================================================
// Systems (Head & Neck specific)
// ============================================================================

const systems = [
  {
    name: 'Skeletal System',
    slug: 'skeletal',
    description: 'Cranial and facial bones, cervical vertebrae',
    color_code: '#F5F0E6',
  },
  {
    name: 'Muscular System',
    slug: 'muscular',
    description: 'Muscles of facial expression, mastication, and neck movement',
    color_code: '#C45C5C',
  },
  {
    name: 'Vascular System',
    slug: 'vascular',
    description: 'Carotid arteries, jugular veins, and cranial blood supply',
    color_code: '#D64545',
  },
  {
    name: 'Nervous System',
    slug: 'nervous',
    description: 'Brain, cranial nerves (I-XII), and cervical plexus',
    color_code: '#E6C744',
  },
  {
    name: 'Special Senses',
    slug: 'special-senses',
    description: 'Eyes, ears, nose, and taste structures',
    color_code: '#9370DB',
  },
];

// ============================================================================
// Structures (70+ anatomical structures)
// ============================================================================

const structures = [
  // ========================================
  // SKULL BONES (Neurocranium & Viscerocranium)
  // ========================================
  {
    canonical_name: 'Frontal bone',
    common_names: ['Forehead bone'],
    latin_name: 'Os frontale',
    pronunciation_ipa: '/ˈfrʌntəl boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Large bone forming the forehead and superior orbital margins.',
    description_full: `The frontal bone is a single midline bone forming the forehead, roof of the orbits, and anterior cranial fossa floor. It consists of a vertical squamous part and horizontal orbital parts.\n\nKey features include:\n- Supraorbital margins with supraorbital notches/foramina\n- Glabella (smooth area between eyebrows)\n- Frontal sinuses (paired air cells)\n- Metopic suture (fetal, usually fuses by age 8)`,
    clinical_significance: 'Frontal bone fractures may involve the frontal sinus, causing CSF rhinorrhea. The supraorbital nerve (V1) exits through the supraorbital foramen. Frontal sinusitis is common.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Supraorbital and supratrochlear arteries',
    model_reference: 'frontal_bone',
    difficulty_rating: 2,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Parietal bone',
    common_names: ['Crown bone'],
    latin_name: 'Os parietale',
    pronunciation_ipa: '/pəˈraɪətəl boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Paired bones forming the superior and lateral skull vault.',
    description_full: `The parietal bones are paired, quadrilateral bones forming the sides and roof of the cranium. They articulate at the sagittal suture superiorly.\n\nSutures:\n- Sagittal suture (medial)\n- Coronal suture (anterior, with frontal)\n- Lambdoid suture (posterior, with occipital)\n- Squamous suture (lateral, with temporal)`,
    clinical_significance: 'Parietal fractures are common in head trauma. The middle meningeal artery runs beneath, making epidural hematoma a risk. Parietal foramina transmit emissary veins.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Middle meningeal artery (internal), superficial temporal artery (external)',
    model_reference: 'parietal_bone',
    difficulty_rating: 2,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Temporal bone',
    common_names: ['Temple bone'],
    latin_name: 'Os temporale',
    pronunciation_ipa: '/ˈtɛmpərəl boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Complex paired bone housing the middle and inner ear structures.',
    description_full: `The temporal bone is a complex bone with four parts:\n\n1. **Squamous part**: Thin, scale-like, forms temporal fossa\n2. **Petrous part**: Dense, pyramid-shaped, contains inner ear\n3. **Mastoid part**: Contains air cells, mastoid process\n4. **Tympanic part**: Forms external acoustic meatus\n\nKey structures:\n- Mandibular fossa (TMJ articulation)\n- Styloid process\n- Carotid canal\n- Jugular foramen`,
    clinical_significance: 'Temporal bone fractures can cause hearing loss, facial nerve paralysis (CN VII), and CSF otorrhea. Mastoiditis is infection of mastoid air cells. TMJ dysfunction is common.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Middle meningeal, superficial temporal, posterior auricular arteries',
    model_reference: 'temporal_bone',
    difficulty_rating: 4,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Occipital bone',
    common_names: ['Back of skull'],
    latin_name: 'Os occipitale',
    pronunciation_ipa: '/ɒkˈsɪpɪtəl boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Bone forming the posterior skull base and foramen magnum.',
    description_full: `The occipital bone forms the back and base of the skull. It surrounds the foramen magnum, where the spinal cord connects to the brain.\n\nParts:\n- Squamous part (posterior)\n- Basilar part (anterior to foramen magnum)\n- Two lateral condylar parts\n\nKey features:\n- Foramen magnum\n- Occipital condyles (articulate with atlas)\n- External occipital protuberance (inion)\n- Hypoglossal canals`,
    clinical_significance: 'Foramen magnum herniation (tonsillar) is life-threatening. Occipital condyle fractures affect atlantooccipital stability. Hypoglossal nerve (CN XII) passes through hypoglossal canal.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Occipital artery, vertebral artery',
    model_reference: 'occipital_bone',
    difficulty_rating: 3,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Sphenoid bone',
    common_names: ['Wedge bone', 'Bat bone'],
    latin_name: 'Os sphenoidale',
    pronunciation_ipa: '/ˈsfiːnɔɪd boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Butterfly-shaped bone at the skull base with numerous foramina.',
    description_full: `The sphenoid is a complex central bone articulating with all other cranial bones. Shaped like a bat with wings spread.\n\nComponents:\n- **Body**: Contains sphenoid sinus, sella turcica (pituitary fossa)\n- **Greater wings**: Form lateral skull base, part of orbit\n- **Lesser wings**: Form posterior orbit roof\n- **Pterygoid processes**: Descend inferiorly\n\nKey foramina:\n- Optic canal (CN II, ophthalmic artery)\n- Superior orbital fissure (CN III, IV, V1, VI)\n- Foramen rotundum (CN V2)\n- Foramen ovale (CN V3)\n- Foramen spinosum (middle meningeal artery)`,
    clinical_significance: 'Pituitary tumors may erode sella turcica. Sphenoid sinusitis can spread to cavernous sinus. Pterion (junction with parietal/frontal/temporal) is thinnest skull point - middle meningeal artery vulnerability.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Middle meningeal artery, internal carotid branches',
    model_reference: 'sphenoid_bone',
    difficulty_rating: 5,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Ethmoid bone',
    common_names: ['Sieve bone'],
    latin_name: 'Os ethmoidale',
    pronunciation_ipa: '/ˈɛθmɔɪd boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Delicate midline bone forming nasal cavity roof and medial orbit.',
    description_full: `The ethmoid bone is a light, spongy bone forming the medial orbit walls, nasal roof, and nasal septum.\n\nComponents:\n- **Cribriform plate**: Perforated horizontal plate (olfactory nerve fibers pass through)\n- **Crista galli**: Vertical midline projection (falx cerebri attachment)\n- **Perpendicular plate**: Forms superior nasal septum\n- **Lateral masses**: Contain ethmoid air cells, form medial orbit (lamina papyracea)\n\nNasal conchae:\n- Superior nasal concha\n- Middle nasal concha`,
    clinical_significance: 'Cribriform plate fractures cause CSF rhinorrhea and anosmia (CN I damage). Ethmoid sinusitis may spread to orbit causing orbital cellulitis. Lamina papyracea is extremely thin - sinus infection risk.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior and posterior ethmoidal arteries',
    model_reference: 'ethmoid_bone',
    difficulty_rating: 4,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Maxilla',
    common_names: ['Upper jaw'],
    latin_name: 'Maxilla',
    pronunciation_ipa: '/mækˈsɪlə/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Paired bones forming the upper jaw, palate, and midface.',
    description_full: `The maxillae are paired bones forming the upper jaw, hard palate, inferior orbital floor, and lateral nasal walls.\n\nProcesses:\n- **Frontal process**: Ascends to frontal bone\n- **Zygomatic process**: Lateral, articulates with zygomatic bone\n- **Palatine process**: Forms anterior hard palate\n- **Alveolar process**: Contains upper teeth sockets\n\nKey features:\n- Maxillary sinus (largest paranasal sinus)\n- Infraorbital foramen (CN V2 infraorbital nerve)\n- Incisive canal`,
    clinical_significance: 'Le Fort fractures classify midface trauma (I-III). Maxillary sinusitis is extremely common. Infraorbital nerve blocks used for dental/facial procedures. Cleft palate involves palatine processes.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Maxillary artery branches, infraorbital artery',
    model_reference: 'maxilla',
    difficulty_rating: 3,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Mandible',
    common_names: ['Lower jaw', 'Jawbone'],
    latin_name: 'Mandibula',
    pronunciation_ipa: '/ˈmændɪbəl/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Horseshoe-shaped bone forming the lower jaw and chin.',
    description_full: `The mandible is the largest, strongest facial bone and the only movable skull bone. It forms the lower jaw.\n\nParts:\n- **Body**: Horizontal portion containing teeth\n- **Ramus**: Vertical portion (right and left)\n- **Angle**: Junction of body and ramus\n\nProcesses:\n- **Condylar process**: Articulates at TMJ\n- **Coronoid process**: Temporalis muscle insertion\n\nForamina:\n- Mandibular foramen (medial ramus - inferior alveolar nerve)\n- Mental foramen (body - mental nerve)`,
    clinical_significance: 'Mandibular fractures are common (often bilateral). Inferior alveolar nerve blocks provide dental anesthesia. TMJ disorders cause jaw pain and clicking. Mandibular dislocation occurs with wide mouth opening.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Inferior alveolar artery, facial artery',
    model_reference: 'mandible',
    difficulty_rating: 3,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Zygomatic bone',
    common_names: ['Cheekbone', 'Malar bone'],
    latin_name: 'Os zygomaticum',
    pronunciation_ipa: '/ˌzaɪɡəˈmætɪk boʊn/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Paired bones forming the cheek prominence and lateral orbit.',
    description_full: `The zygomatic bones form the prominence of the cheeks and contribute to the lateral orbital wall and floor.\n\nProcesses:\n- **Frontal process**: Articulates with frontal bone\n- **Temporal process**: Forms zygomatic arch with temporal bone\n- **Maxillary process**: Articulates with maxilla\n\nContains zygomaticofacial and zygomaticotemporal foramina for nerves.`,
    clinical_significance: 'Zygomatic fractures ("tripod fractures") are common in facial trauma. May cause orbital floor fractures with diplopia and infraorbital nerve paresthesia. Zygomatic arch fractures impair mandibular movement.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Maxillary artery branches, transverse facial artery',
    model_reference: 'zygomatic_bone',
    difficulty_rating: 2,
    prerequisite_names: [],
  },

  // ========================================
  // FACIAL MUSCLES
  // ========================================
  {
    canonical_name: 'Orbicularis oculi',
    common_names: ['Eye sphincter muscle'],
    latin_name: 'Musculus orbicularis oculi',
    pronunciation_ipa: '/ˌɔːrbɪkjʊˈlɛərɪs ˈɒkjʊlaɪ/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Sphincter muscle surrounding the eye, responsible for eyelid closure.',
    description_full: `The orbicularis oculi is the primary muscle of eyelid closure, consisting of three parts:\n\n1. **Orbital part**: Outer portion, forceful eye closure (squinting)\n2. **Palpebral part**: Within eyelids, gentle closure (blinking)\n3. **Lacrimal part**: Deep fibers near lacrimal sac\n\nCircular fibers surround the orbit and eyelids.`,
    clinical_significance: 'Facial nerve (CN VII) paralysis causes inability to close eye, leading to corneal exposure and drying. Bell\'s palsy affects this muscle. Blepharospasm is involuntary contraction.',
    origin: 'Medial orbital margin, medial palpebral ligament, lacrimal bone',
    insertion: 'Skin around orbit, lateral palpebral raphe',
    action: 'Eyelid closure, blinking, squinting, assists lacrimal drainage',
    innervation: 'Facial nerve (CN VII) - temporal and zygomatic branches',
    blood_supply: 'Facial artery, superficial temporal artery, ophthalmic artery',
    model_reference: 'orbicularis_oculi',
    difficulty_rating: 3,
    prerequisite_names: ['Frontal bone', 'Zygomatic bone'],
  },
  {
    canonical_name: 'Orbicularis oris',
    common_names: ['Lip sphincter muscle'],
    latin_name: 'Musculus orbicularis oris',
    pronunciation_ipa: '/ˌɔːrbɪkjʊˈlɛərɪs ˈɔːrɪs/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Sphincter muscle encircling the mouth, controls lip movement.',
    description_full: `The orbicularis oris is a complex muscle encircling the mouth opening. It consists of intrinsic fibers within the lips and extrinsic fibers from other facial muscles.\n\nFunctionally divided into:\n- **Superficial part**: Larger movements\n- **Deep part**: Fine motor control\n\nServes as the sphincter of the oral cavity.`,
    clinical_significance: 'Facial nerve palsy causes drooping of mouth corner and drooling. Essential for speech articulation (labial sounds: p, b, m). Used in cosmetic procedures. Whistling requires intact function.',
    origin: 'Multiple origins from surrounding facial muscles and maxilla/mandible',
    insertion: 'Skin and mucosa of lips, modiolus',
    action: 'Lip closure, protrusion, pursing; speech articulation, kissing, whistling',
    innervation: 'Facial nerve (CN VII) - buccal and mandibular branches',
    blood_supply: 'Superior and inferior labial arteries (facial artery branches)',
    model_reference: 'orbicularis_oris',
    difficulty_rating: 3,
    prerequisite_names: ['Maxilla', 'Mandible'],
  },
  {
    canonical_name: 'Masseter',
    common_names: ['Chewing muscle'],
    latin_name: 'Musculus masseter',
    pronunciation_ipa: '/mæˈsiːtər/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Powerful muscle of mastication elevating the mandible.',
    description_full: `The masseter is a thick, powerful, rectangular muscle forming the prominence of the cheek. It is the most superficial muscle of mastication.\n\nTwo parts:\n- **Superficial part**: Larger, descends inferoposteriorly\n- **Deep part**: Smaller, more vertical fibers\n\nOne of the strongest muscles in the human body relative to size.`,
    clinical_significance: 'Masseter hypertrophy can occur with bruxism (teeth grinding). Palpable during jaw clenching. Used in Botox treatment for bruxism and facial slimming. Masseteric nerve block for dental procedures.',
    origin: 'Zygomatic arch (superficial: inferior border; deep: medial surface)',
    insertion: 'Lateral surface of mandibular ramus and angle',
    action: 'Elevates mandible (closes jaw), assists in protrusion',
    innervation: 'Masseteric nerve (branch of mandibular division of trigeminal nerve, CN V3)',
    blood_supply: 'Masseteric artery (from maxillary artery), transverse facial artery',
    model_reference: 'masseter',
    difficulty_rating: 2,
    prerequisite_names: ['Zygomatic bone', 'Mandible'],
  },
  {
    canonical_name: 'Temporalis',
    common_names: ['Temple muscle'],
    latin_name: 'Musculus temporalis',
    pronunciation_ipa: '/ˌtɛmpəˈreɪlɪs/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Fan-shaped muscle of mastication in the temporal fossa.',
    description_full: `The temporalis is a large, fan-shaped muscle occupying the temporal fossa. It is the most powerful muscle of mastication.\n\nThe muscle fibers converge inferiorly, passing deep to the zygomatic arch to insert on the coronoid process.\n\nFiber orientation:\n- Anterior fibers: More vertical (elevation)\n- Posterior fibers: More horizontal (retraction)`,
    clinical_significance: 'Temporal arteritis affects the temporal arteries overlying this muscle. Visible wasting in malnutrition/cachexia. Temporal headaches often localize here. Coronoid process fractures affect insertion.',
    origin: 'Temporal fossa (temporal and parietal bones), temporal fascia',
    insertion: 'Coronoid process and anterior border of mandibular ramus',
    action: 'Elevates mandible (jaw closure), posterior fibers retract mandible',
    innervation: 'Deep temporal nerves (anterior and posterior, from CN V3)',
    blood_supply: 'Deep temporal arteries (anterior and posterior, from maxillary artery)',
    model_reference: 'temporalis',
    difficulty_rating: 3,
    prerequisite_names: ['Temporal bone', 'Parietal bone', 'Mandible'],
  },
  {
    canonical_name: 'Frontalis',
    common_names: ['Forehead muscle'],
    latin_name: 'Musculus frontalis',
    pronunciation_ipa: '/frʌnˈteɪlɪs/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: 'Occipitofrontalis',
    definition_brief: 'Muscle raising the eyebrows and wrinkling the forehead.',
    description_full: `The frontalis is the anterior belly of the occipitofrontalis muscle. It is a thin, quadrilateral muscle covering the forehead.\n\nPart of the scalp musculature connected posteriorly to occipitalis via the epicranial aponeurosis (galea aponeurotica).\n\nNo bony attachments - attaches to skin and fascia.`,
    clinical_significance: 'Facial nerve paralysis causes inability to raise eyebrow on affected side (important diagnostic sign). Frontalis recruitment in ptosis. Botox target for forehead wrinkles. Raises eyebrow in surprise expression.',
    origin: 'Epicranial aponeurosis (galea aponeurotica)',
    insertion: 'Skin of eyebrows and root of nose',
    action: 'Raises eyebrows, wrinkles forehead horizontally (expression of surprise)',
    innervation: 'Facial nerve (CN VII) - temporal branch',
    blood_supply: 'Supraorbital and supratrochlear arteries (ophthalmic artery branches)',
    model_reference: 'frontalis',
    difficulty_rating: 2,
    prerequisite_names: ['Frontal bone'],
  },

  // ========================================
  // NECK MUSCLES
  // ========================================
  {
    canonical_name: 'Sternocleidomastoid',
    common_names: ['SCM', 'Neck strap muscle'],
    latin_name: 'Musculus sternocleidomastoideus',
    pronunciation_ipa: '/ˌstɜːrnoʊˌklaɪdoʊˈmæstɔɪd/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Prominent bilateral neck muscle for head rotation and flexion.',
    description_full: `The sternocleidomastoid (SCM) is a large, prominent muscle forming a landmark in the neck, dividing it into anterior and posterior triangles.\n\nTwo heads:\n- **Sternal head**: Larger, more anterior, from manubrium\n- **Clavicular head**: Smaller, more lateral, from medial clavicle\n\nThe two heads unite and ascend obliquely to the mastoid process.\n\nBilateral contraction: Neck flexion\nUnilateral contraction: Ipsilateral lateral flexion, contralateral rotation`,
    clinical_significance: 'Torticollis (wry neck) involves SCM spasm/shortening. Accessory nerve (CN XI) injury causes weakness. Divides neck into surgical triangles. Palpable landmark for central line placement. Congenital muscular torticollis in infants.',
    origin: 'Sternal head: manubrium of sternum; Clavicular head: medial third of clavicle',
    insertion: 'Mastoid process of temporal bone, superior nuchal line of occipital bone',
    action: 'Unilateral: ipsilateral lateral flexion, contralateral rotation; Bilateral: neck flexion, assists in forced inspiration',
    innervation: 'Accessory nerve (CN XI - motor), C2-C3 spinal nerves (proprioception)',
    blood_supply: 'Occipital artery, superior thyroid artery, suprascapular artery',
    model_reference: 'sternocleidomastoid',
    difficulty_rating: 2,
    prerequisite_names: ['Temporal bone', 'Occipital bone'],
  },
  {
    canonical_name: 'Anterior scalene',
    common_names: ['Scalenus anterior'],
    latin_name: 'Musculus scalenus anterior',
    pronunciation_ipa: '/skeɪˈliːnəs ænˈtɪəriər/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Lateral neck muscle elevating the first rib and flexing the neck.',
    description_full: `The anterior scalene is the most anterior of the three scalene muscles. It forms the anterior border of the interscalene triangle.\n\nImportant anatomical relations:\n- Subclavian vein passes anterior\n- Subclavian artery and brachial plexus pass posterior (through interscalene triangle)\n- Phrenic nerve descends on its anterior surface`,
    clinical_significance: 'Thoracic outlet syndrome can involve anterior scalene hypertrophy/spasm compressing brachial plexus or subclavian vessels. Interscalene block targets brachial plexus between anterior and middle scalene. Phrenic nerve injury risk.',
    origin: 'Transverse processes of C3-C6 vertebrae (anterior tubercles)',
    insertion: 'Scalene tubercle on first rib',
    action: 'Unilateral: ipsilateral lateral flexion, contralateral rotation; Bilateral: neck flexion, elevates first rib (forced inspiration)',
    innervation: 'Ventral rami of C5-C7 spinal nerves',
    blood_supply: 'Ascending cervical artery, inferior thyroid artery',
    model_reference: 'scalene_anterior',
    difficulty_rating: 4,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Trapezius',
    common_names: ['Trap'],
    latin_name: 'Musculus trapezius',
    pronunciation_ipa: '/trəˈpiːziəs/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Large triangular muscle moving the scapula and extending the neck.',
    description_full: `The trapezius is a large, superficial, triangular muscle extending from the skull and vertebral column to the shoulder girdle.\n\nThree functional parts:\n1. **Upper (descending) fibers**: Elevate scapula\n2. **Middle (transverse) fibers**: Retract scapula\n3. **Lower (ascending) fibers**: Depress scapula\n\nBilaterally, the muscles form a trapezoid shape.`,
    clinical_significance: 'Accessory nerve (CN XI) injury causes shoulder droop and inability to shrug. Trapezius strain common with poor posture. Trigger points cause neck/shoulder pain. Scapular winging if denervated.',
    origin: 'External occipital protuberance, superior nuchal line, ligamentum nuchae, spinous processes C7-T12',
    insertion: 'Lateral third of clavicle, acromion, spine of scapula',
    action: 'Upper: elevates scapula; Middle: retracts scapula; Lower: depresses scapula; Rotates scapula for arm elevation; Bilateral: extends neck',
    innervation: 'Accessory nerve (CN XI - motor), C3-C4 spinal nerves (proprioception)',
    blood_supply: 'Transverse cervical artery, dorsal scapular artery',
    model_reference: 'trapezius',
    difficulty_rating: 2,
    prerequisite_names: ['Occipital bone'],
  },
  {
    canonical_name: 'Platysma',
    common_names: ['Neck skin muscle'],
    latin_name: 'Platysma',
    pronunciation_ipa: '/pləˈtɪzmə/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Thin, superficial muscle of facial expression in the neck.',
    description_full: `The platysma is a broad, thin sheet of muscle in the superficial fascia of the neck. It is the most superficial neck muscle.\n\nExtends from the chest and shoulder upward to the mandible and face. Fibers are continuous with facial muscles at the mandibular border.\n\nFibers run obliquely upward and medially.`,
    clinical_significance: 'Facial nerve injury affects platysma. Visible during straining/emotional expression. Must be considered in neck surgery. "Turkey neck" appearance with aging relates to platysma laxity. Rare to test clinically.',
    origin: 'Fascia covering pectoralis major and deltoid',
    insertion: 'Lower border of mandible, skin of lower face, angle of mouth, modiolus',
    action: 'Depresses mandible, tenses neck skin, draws corners of mouth downward (grimacing)',
    innervation: 'Facial nerve (CN VII) - cervical branch',
    blood_supply: 'Submental artery, suprascapular artery',
    model_reference: 'platysma',
    difficulty_rating: 2,
    prerequisite_names: ['Mandible'],
  },

  // ========================================
  // CRANIAL NERVES (All 12)
  // ========================================
  {
    canonical_name: 'Olfactory nerve',
    common_names: ['CN I', 'Nerve of smell'],
    latin_name: 'Nervus olfactorius',
    pronunciation_ipa: '/ɒlˈfæktəri nɜːrv/',
    system_slugs: ['nervous', 'special-senses'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'First cranial nerve carrying olfactory sensory information from nasal cavity.',
    description_full: `The olfactory nerve (CN I) consists of approximately 20 bundles of unmyelinated axons arising from olfactory receptor neurons in the nasal mucosa.\n\nCourse:\n1. Olfactory receptor cells in superior nasal cavity\n2. Axons pass through cribriform plate of ethmoid bone\n3. Synapse in olfactory bulb\n4. Project to primary olfactory cortex via olfactory tract\n\nOnly cranial nerve with neurons that regenerate throughout life.`,
    clinical_significance: 'Anosmia (loss of smell) occurs with cribriform plate fractures, viral infections (COVID-19), neurodegenerative diseases (Parkinson\'s, Alzheimer\'s). Olfactory groove meningiomas compress nerve. Hyposmia common with aging.',
    origin: 'Olfactory epithelium in superior nasal cavity',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior and posterior ethmoidal arteries',
    model_reference: 'cn_1_olfactory',
    difficulty_rating: 2,
    prerequisite_names: ['Ethmoid bone'],
  },
  {
    canonical_name: 'Optic nerve',
    common_names: ['CN II', 'Nerve of sight'],
    latin_name: 'Nervus opticus',
    pronunciation_ipa: '/ˈɒptɪk nɜːrv/',
    system_slugs: ['nervous', 'special-senses'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Second cranial nerve transmitting visual information from retina to brain.',
    description_full: `The optic nerve (CN II) is actually a CNS tract (not a true peripheral nerve) transmitting visual information from the retina to the brain.\n\nCourse:\n1. Retinal ganglion cell axons converge at optic disc\n2. Nerve exits orbit through optic canal\n3. Optic chiasm (partial decussation - nasal fibers cross)\n4. Optic tracts to lateral geniculate nucleus\n5. Optic radiations to primary visual cortex\n\nContains approximately 1.2 million axons.`,
    clinical_significance: 'Optic neuritis causes vision loss and pain with eye movement (multiple sclerosis). Papilledema indicates increased intracranial pressure. Optic nerve gliomas in NF1. Glaucoma damages nerve. Visual field defects localize lesions.',
    origin: 'Retinal ganglion cells',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Ophthalmic artery, central retinal artery',
    model_reference: 'cn_2_optic',
    difficulty_rating: 3,
    prerequisite_names: ['Sphenoid bone'],
  },
  {
    canonical_name: 'Oculomotor nerve',
    common_names: ['CN III', 'Eye movement nerve'],
    latin_name: 'Nervus oculomotorius',
    pronunciation_ipa: '/ˌɒkjʊloʊˈmoʊtər nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Third cranial nerve controlling most extraocular muscles and pupil constriction.',
    description_full: `The oculomotor nerve (CN III) controls most eye movements, pupil constriction, and lens accommodation.\n\nComponents:\n- **Motor (somatic)**: Superior rectus, inferior rectus, medial rectus, inferior oblique, levator palpebrae superioris\n- **Motor (parasympathetic)**: Sphincter pupillae, ciliary muscle\n\nCourse:\n1. Emerges from midbrain (interpeduncular fossa)\n2. Passes between posterior cerebral and superior cerebellar arteries\n3. Runs in cavernous sinus lateral wall\n4. Enters orbit through superior orbital fissure\n5. Divides into superior and inferior divisions`,
    clinical_significance: 'CN III palsy causes "down and out" eye position, ptosis, dilated pupil. Posterior communicating artery aneurysm compresses nerve (pupil involvement). Diabetic CN III palsy typically spares pupil. Uncal herniation causes compression.',
    origin: 'Oculomotor nucleus in midbrain',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of internal carotid and posterior cerebral arteries',
    model_reference: 'cn_3_oculomotor',
    difficulty_rating: 4,
    prerequisite_names: ['Sphenoid bone'],
  },
  {
    canonical_name: 'Trochlear nerve',
    common_names: ['CN IV'],
    latin_name: 'Nervus trochlearis',
    pronunciation_ipa: '/ˈtrɒkliər nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Fourth cranial nerve innervating the superior oblique muscle.',
    description_full: `The trochlear nerve (CN IV) is the smallest cranial nerve by number of axons and the only one to emerge from the dorsal brainstem.\n\nUnique features:\n- Only cranial nerve to decussate completely\n- Longest intracranial course\n- Only nerve exiting dorsally from brainstem\n\nInnervates only the superior oblique muscle.\n\nCourse:\n1. Emerges from dorsal midbrain (crosses to opposite side)\n2. Circles around brainstem\n3. Runs in cavernous sinus lateral wall\n4. Enters orbit through superior orbital fissure`,
    clinical_significance: 'CN IV palsy causes vertical diplopia (worse when looking down and in - reading stairs). Head tilt to opposite side (compensatory). Most common cause is trauma (long course makes it vulnerable). Congenital palsy often asymptomatic.',
    origin: 'Trochlear nucleus in midbrain (decussates)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of posterior cerebral artery',
    model_reference: 'cn_4_trochlear',
    difficulty_rating: 3,
    prerequisite_names: ['Sphenoid bone'],
  },
  {
    canonical_name: 'Trigeminal nerve',
    common_names: ['CN V', 'Fifth nerve'],
    latin_name: 'Nervus trigeminus',
    pronunciation_ipa: '/traɪˈdʒɛmɪnəl nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Fifth cranial nerve providing facial sensation and motor to mastication muscles.',
    description_full: `The trigeminal nerve (CN V) is the largest cranial nerve, responsible for facial sensation and motor control of mastication muscles.\n\nThree divisions (all sensory + motor in V3):\n1. **V1 - Ophthalmic**: Forehead, upper eyelid, cornea → superior orbital fissure\n2. **V2 - Maxillary**: Midface, upper teeth, palate → foramen rotundum\n3. **V3 - Mandibular**: Lower face, lower teeth, anterior tongue, mastication muscles → foramen ovale\n\nTrigeminal ganglion (semilunar ganglion) in Meckel's cave contains sensory cell bodies.`,
    clinical_significance: 'Trigeminal neuralgia causes severe facial pain. Shingles (herpes zoster) affects V1 commonly. Corneal reflex tests V1 (afferent) and CN VII (efferent). Dental procedures require V2/V3 blocks. Multiple sclerosis can affect nerve.',
    origin: 'Trigeminal ganglion (sensory), motor nucleus in pons (motor)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of internal carotid and maxillary arteries',
    model_reference: 'cn_5_trigeminal',
    difficulty_rating: 5,
    prerequisite_names: ['Sphenoid bone'],
  },
  {
    canonical_name: 'Abducens nerve',
    common_names: ['CN VI'],
    latin_name: 'Nervus abducens',
    pronunciation_ipa: '/æbˈdjuːsənz nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Sixth cranial nerve innervating the lateral rectus muscle.',
    description_full: `The abducens nerve (CN VI) innervates only the lateral rectus muscle, which abducts the eye.\n\nCourse:\n1. Emerges from pontomedullary junction\n2. Longest subarachnoid course (vulnerable to injury)\n3. Pierces dura near dorsum sellae\n4. Passes through cavernous sinus (only nerve not in lateral wall - runs through sinus with ICA)\n5. Enters orbit through superior orbital fissure\n\nRuns alongside internal carotid artery in cavernous sinus.`,
    clinical_significance: 'CN VI palsy causes horizontal diplopia (worse with lateral gaze), esotropia, inability to abduct eye. Most common cause: increased intracranial pressure (false localizing sign). Also: diabetes, stroke, trauma.',
    origin: 'Abducens nucleus in pons',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of basilar and internal carotid arteries',
    model_reference: 'cn_6_abducens',
    difficulty_rating: 3,
    prerequisite_names: ['Sphenoid bone'],
  },
  {
    canonical_name: 'Facial nerve',
    common_names: ['CN VII', 'Seventh nerve'],
    latin_name: 'Nervus facialis',
    pronunciation_ipa: '/ˈfeɪʃəl nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Seventh cranial nerve controlling facial expression muscles and taste.',
    description_full: `The facial nerve (CN VII) has motor, sensory, and parasympathetic functions.\n\nComponents:\n- **Motor**: Muscles of facial expression, stapedius, stylohyoid, posterior digastric\n- **Sensory (taste)**: Anterior 2/3 of tongue via chorda tympani\n- **Parasympathetic**: Lacrimal, submandibular, sublingual glands\n\nCourse:\n1. Emerges from pontomedullary junction with nervus intermedius\n2. Enters internal acoustic meatus\n3. Facial canal in temporal bone (complex course)\n4. Exits stylomastoid foramen\n5. Enters parotid gland (5 terminal branches: temporal, zygomatic, buccal, mandibular, cervical)`,
    clinical_significance: 'Bell\'s palsy (idiopathic) causes sudden facial paralysis. Ramsey Hunt syndrome (herpes zoster). Parotid tumors may involve nerve. Acoustic neuroma affects nerve. Stroke (UMN) spares forehead. Tests: raise eyebrows, close eyes, smile.',
    origin: 'Facial nucleus in pons, superior salivatory nucleus',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Labyrinthine artery, stylomastoid artery',
    model_reference: 'cn_7_facial',
    difficulty_rating: 5,
    prerequisite_names: ['Temporal bone'],
  },
  {
    canonical_name: 'Vestibulocochlear nerve',
    common_names: ['CN VIII', 'Auditory-vestibular nerve'],
    latin_name: 'Nervus vestibulocochlearis',
    pronunciation_ipa: '/vɛˌstɪbjʊloʊˈkɒkliər nɜːrv/',
    system_slugs: ['nervous', 'special-senses'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Eighth cranial nerve for hearing and balance.',
    description_full: `The vestibulocochlear nerve (CN VIII) has two distinct functional components:\n\n1. **Cochlear division**: Hearing\n   - Spiral ganglion cells\n   - From organ of Corti in cochlea\n\n2. **Vestibular division**: Balance and spatial orientation\n   - Vestibular ganglion (Scarpa's ganglion)\n   - From semicircular canals, utricle, saccule\n\nCourse:\n- Emerges from pontomedullary junction\n- Enters internal acoustic meatus with CN VII\n- Terminates in cochlear and vestibular nuclei in pons/medulla`,
    clinical_significance: 'Acoustic neuroma (vestibular schwannoma) causes hearing loss, tinnitus, balance problems. Ménière\'s disease affects vestibular system. Labyrinthitis causes vertigo. Weber and Rinne tests assess hearing. BPPV involves vestibular component.',
    origin: 'Spiral ganglion (cochlear), vestibular ganglion (vestibular)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Labyrinthine artery (from AICA)',
    model_reference: 'cn_8_vestibulocochlear',
    difficulty_rating: 4,
    prerequisite_names: ['Temporal bone'],
  },
  {
    canonical_name: 'Glossopharyngeal nerve',
    common_names: ['CN IX', 'Ninth nerve'],
    latin_name: 'Nervus glossopharyngeus',
    pronunciation_ipa: '/ˌɡlɒsoʊfəˈrɪndʒiəl nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Ninth cranial nerve for throat sensation, taste, and swallowing.',
    description_full: `The glossopharyngeal nerve (CN IX) has motor, sensory, and parasympathetic functions.\n\nComponents:\n- **Motor**: Stylopharyngeus muscle\n- **Sensory**: Posterior 1/3 tongue (taste and general), pharynx, middle ear, carotid body/sinus\n- **Parasympathetic**: Parotid gland (via otic ganglion)\n\nCourse:\n1. Emerges from medulla\n2. Exits skull via jugular foramen (with X and XI)\n3. Superior and inferior ganglia in jugular foramen\n4. Descends between internal and external carotid arteries`,
    clinical_significance: 'Isolated CN IX lesions rare (usually involves X, XI). Gag reflex tests IX (afferent) and X (efferent). Glossopharyngeal neuralgia causes throat pain. Carotid sinus syncope involves CN IX. Parotid surgery may damage nerve.',
    origin: 'Multiple nuclei in medulla',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of vertebral and external carotid arteries',
    model_reference: 'cn_9_glossopharyngeal',
    difficulty_rating: 4,
    prerequisite_names: ['Temporal bone', 'Occipital bone'],
  },
  {
    canonical_name: 'Vagus nerve',
    common_names: ['CN X', 'Tenth nerve', 'Wandering nerve'],
    latin_name: 'Nervus vagus',
    pronunciation_ipa: '/ˈveɪɡəs nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Tenth cranial nerve providing parasympathetic innervation to thoracic and abdominal viscera.',
    description_full: `The vagus nerve (CN X) is the longest cranial nerve with the most extensive distribution (Latin "vagus" = wandering).\n\nComponents:\n- **Motor**: Pharynx, larynx (speech and swallowing)\n- **Sensory**: Larynx, pharynx, external ear, dura\n- **Parasympathetic**: Heart, lungs, GI tract to splenic flexure\n\nCourse:\n1. Emerges from medulla\n2. Exits via jugular foramen\n3. Descends in carotid sheath\n4. Thorax and abdomen\n\nKey branches: Superior/recurrent laryngeal nerves, cardiac branches, pulmonary plexus, gastric branches`,
    clinical_significance: 'Recurrent laryngeal nerve injury (thyroid surgery) causes hoarseness. Vagal nerve stimulation treats epilepsy. Carotid endarterectomy may damage nerve. Uvula deviates away from lesion. Vasovagal syncope involves vagal activation.',
    origin: 'Multiple nuclei in medulla (dorsal motor nucleus, nucleus ambiguus, solitary nucleus)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of vertebral, posterior inferior cerebellar arteries',
    model_reference: 'cn_10_vagus',
    difficulty_rating: 5,
    prerequisite_names: ['Temporal bone', 'Occipital bone'],
  },
  {
    canonical_name: 'Accessory nerve',
    common_names: ['CN XI', 'Spinal accessory nerve'],
    latin_name: 'Nervus accessorius',
    pronunciation_ipa: '/ækˈsɛsəri nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Eleventh cranial nerve innervating trapezius and sternocleidomastoid muscles.',
    description_full: `The accessory nerve (CN XI) is purely motor, innervating trapezius and sternocleidomastoid muscles.\n\nTwo components (now considered CN XI is only spinal part):\n- **Spinal part**: From C1-C5 spinal cord\n- **Cranial part**: Actually part of vagus nerve (CN X)\n\nCourse:\n1. Spinal rootlets ascend through foramen magnum\n2. Joins briefly with vagal fibers\n3. Exits via jugular foramen\n4. Descends in posterior triangle of neck\n5. Innervates SCM, then continues to trapezius`,
    clinical_significance: 'Injury during neck dissection/lymph node biopsy causes shoulder droop, inability to shrug, scapular winging. Damage in posterior triangle is common. Test: shoulder shrug (trapezius) and head turn against resistance (SCM).',
    origin: 'Spinal accessory nucleus (C1-C5 spinal cord)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of vertebral and occipital arteries',
    model_reference: 'cn_11_accessory',
    difficulty_rating: 3,
    prerequisite_names: ['Occipital bone', 'Temporal bone'],
  },
  {
    canonical_name: 'Hypoglossal nerve',
    common_names: ['CN XII', 'Twelfth nerve'],
    latin_name: 'Nervus hypoglossus',
    pronunciation_ipa: '/ˌhaɪpoʊˈɡlɒsəl nɜːrv/',
    system_slugs: ['nervous'],
    structure_type: StructureType.NERVE,
    parent_structure_name: null,
    definition_brief: 'Twelfth cranial nerve controlling tongue movements.',
    description_full: `The hypoglossal nerve (CN XII) is the motor nerve to the tongue, innervating both intrinsic and extrinsic tongue muscles.\n\nInnervates:\n- **Intrinsic muscles**: Superior/inferior longitudinal, transverse, vertical\n- **Extrinsic muscles**: Genioglossus, hyoglossus, styloglossus\n- (Exception: palatoglossus is innervated by CN X)\n\nCourse:\n1. Emerges from medulla\n2. Exits via hypoglossal canal in occipital bone\n3. Descends lateral to internal carotid artery\n4. Passes above hyoid bone\n5. Enters tongue from below`,
    clinical_significance: 'Tongue deviates toward side of lesion (unopposed genioglossus pulls toward weak side). Causes: stroke, tumor, trauma. Bilateral lesions impair speech and swallowing. "LMN: tongue toward, UMN: tongue away" from lesion. Test: tongue protrusion.',
    origin: 'Hypoglossal nucleus in medulla',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of vertebral, ascending pharyngeal, lingual arteries',
    model_reference: 'cn_12_hypoglossal',
    difficulty_rating: 3,
    prerequisite_names: ['Occipital bone'],
  },

  // ========================================
  // VASCULAR STRUCTURES
  // ========================================
  {
    canonical_name: 'Common carotid artery',
    common_names: ['CCA'],
    latin_name: 'Arteria carotis communis',
    pronunciation_ipa: '/ˈkærətɪd ˈɑːrtəri/',
    system_slugs: ['vascular'],
    structure_type: StructureType.ARTERY,
    parent_structure_name: null,
    definition_brief: 'Major artery supplying blood to the head and neck, bifurcating into internal and external carotid arteries.',
    description_full: `The common carotid arteries supply the head and neck. The right arises from the brachiocephalic trunk, the left directly from the aortic arch.\n\nCourse:\n- Ascends in carotid sheath (with internal jugular vein and vagus nerve)\n- No branches in neck\n- Bifurcates at C3-C4 level (carotid bifurcation) into:\n  - Internal carotid artery (ICA)\n  - External carotid artery (ECA)\n\nCarotid sinus (baroreceptor) and carotid body (chemoreceptor) at bifurcation.`,
    clinical_significance: 'Carotid stenosis causes stroke risk. Carotid endarterectomy removes atherosclerotic plaque. Carotid pulse palpable. Carotid sinus massage can treat SVT but may cause bradycardia. Carotid bruit indicates stenosis. Dissection causes stroke.',
    origin: 'Right: brachiocephalic trunk; Left: aortic arch',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'common_carotid_artery',
    difficulty_rating: 2,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Internal carotid artery',
    common_names: ['ICA'],
    latin_name: 'Arteria carotis interna',
    pronunciation_ipa: '/ɪnˈtɜːrnəl kəˈrɒtɪd ˈɑːrtəri/',
    system_slugs: ['vascular'],
    structure_type: StructureType.ARTERY,
    parent_structure_name: 'Common carotid artery',
    definition_brief: 'Artery supplying the brain and eyes, without extracranial branches.',
    description_full: `The internal carotid artery (ICA) is a major source of blood to the brain and orbit.\n\nSegments (Bouthillier classification):\n1. **Cervical**: No branches\n2. **Petrous**: In carotid canal\n3. **Lacerum**: Above foramen lacerum\n4. **Cavernous**: In cavernous sinus\n5. **Clinoid**: Below anterior clinoid process\n6. **Ophthalmic**: Gives ophthalmic artery\n7. **Communicating**: Terminal branches\n\nTerminal branches:\n- Anterior cerebral artery\n- Middle cerebral artery\n- Posterior communicating artery\n- Ophthalmic artery`,
    clinical_significance: 'ICA stenosis causes ipsilateral monocular blindness (amaurosis fugax), contralateral weakness. Dissection causes Horner syndrome. Aneurysms common at Circle of Willis. Cavernous sinus thrombosis may involve ICA. Stroke major complication.',
    origin: 'Common carotid artery bifurcation',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'internal_carotid_artery',
    difficulty_rating: 4,
    prerequisite_names: ['Common carotid artery', 'Temporal bone', 'Sphenoid bone'],
  },
  {
    canonical_name: 'External carotid artery',
    common_names: ['ECA'],
    latin_name: 'Arteria carotis externa',
    pronunciation_ipa: '/ɪkˈstɜːrnəl kəˈrɒtɪd ˈɑːrtəri/',
    system_slugs: ['vascular'],
    structure_type: StructureType.ARTERY,
    parent_structure_name: 'Common carotid artery',
    definition_brief: 'Artery supplying the face, scalp, and neck structures.',
    description_full: `The external carotid artery (ECA) supplies the face, scalp, neck, and meninges.\n\nEight branches (mnemonic: "Some Anatomists Like Freaking Out Poor Medical Students"):\n1. **Superior thyroid**: First branch\n2. **Ascending pharyngeal**: Medial\n3. **Lingual**: Tongue\n4. **Facial**: Face\n5. **Occipital**: Posterior scalp\n6. **Posterior auricular**: Behind ear\n7. **Maxillary**: Terminal branch (deep face)\n8. **Superficial temporal**: Terminal branch (temple)\n\nThe ECA has many anastomoses providing collateral circulation.`,
    clinical_significance: 'Temporal arteritis affects superficial temporal branch. External carotid artery embolization treats severe epistaxis. Facial artery pulse palpable. Maxillary artery supplies nasal cavity (epistaxis source). ECA to ICA anastomoses in vascular disease.',
    origin: 'Common carotid artery bifurcation',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'external_carotid_artery',
    difficulty_rating: 4,
    prerequisite_names: ['Common carotid artery'],
  },
  {
    canonical_name: 'Vertebral artery',
    common_names: ['VA'],
    latin_name: 'Arteria vertebralis',
    pronunciation_ipa: '/ˈvɜːrtɪbrəl ˈɑːrtəri/',
    system_slugs: ['vascular'],
    structure_type: StructureType.ARTERY,
    parent_structure_name: null,
    definition_brief: 'Artery ascending through cervical transverse foramina to supply the posterior brain.',
    description_full: `The vertebral arteries are paired arteries supplying the posterior circulation of the brain.\n\nCourse (4 segments):\n1. **V1 (Preforaminal)**: Origin to C6 transverse foramen\n2. **V2 (Foraminal)**: Through C6-C2 transverse foramina\n3. **V3 (Extradural)**: Loops around C1, enters foramen magnum\n4. **V4 (Intradural)**: Intracranial, unites to form basilar artery\n\nBranches:\n- Anterior/posterior spinal arteries\n- Posterior inferior cerebellar artery (PICA)\n- Meningeal branches`,
    clinical_significance: 'Vertebral artery dissection causes posterior circulation stroke. PICA syndrome (lateral medullary/Wallenberg syndrome). Atherosclerosis causes vertebrobasilar insufficiency. Chiropractic manipulation may cause dissection. Basilar artery thrombosis is life-threatening.',
    origin: 'Subclavian artery (first branch)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'vertebral_artery',
    difficulty_rating: 4,
    prerequisite_names: ['Occipital bone'],
  },
  {
    canonical_name: 'Internal jugular vein',
    common_names: ['IJV'],
    latin_name: 'Vena jugularis interna',
    pronunciation_ipa: '/ɪnˈtɜːrnəl ˈdʒʌɡjʊlər veɪn/',
    system_slugs: ['vascular'],
    structure_type: StructureType.VEIN,
    parent_structure_name: null,
    definition_brief: 'Major vein draining blood from the brain, face, and neck.',
    description_full: `The internal jugular vein (IJV) is the main venous drainage of the brain and face.\n\nCourse:\n- Begins as continuation of sigmoid sinus at jugular foramen\n- Descends in carotid sheath (lateral to carotid artery)\n- Unites with subclavian vein to form brachiocephalic vein\n\nTributaries:\n- Inferior petrosal sinus\n- Facial vein\n- Lingual vein\n- Pharyngeal veins\n- Superior and middle thyroid veins\n\nRight IJV is typically larger and more direct.`,
    clinical_significance: 'Central venous access site (ultrasound-guided). JVP (jugular venous pressure) indicates right heart pressure. Thrombosis may occur with infection/catheters. Lemierre syndrome is septic thrombophlebitis. Rarely, air embolism during central line placement.',
    origin: 'Jugular foramen (continuation of sigmoid sinus)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'internal_jugular_vein',
    difficulty_rating: 3,
    prerequisite_names: ['Temporal bone', 'Occipital bone'],
  },

  // ========================================
  // EYE STRUCTURES
  // ========================================
  {
    canonical_name: 'Globe',
    common_names: ['Eyeball'],
    latin_name: 'Bulbus oculi',
    pronunciation_ipa: '/ɡloʊb/',
    system_slugs: ['special-senses'],
    structure_type: StructureType.ORGAN,
    parent_structure_name: null,
    definition_brief: 'The eyeball containing optical and neural structures for vision.',
    description_full: `The globe (eyeball) is a complex sensory organ for vision, approximately 24mm in diameter.\n\nThree layers:\n1. **Outer fibrous layer**: Sclera (posterior 5/6) and cornea (anterior 1/6)\n2. **Middle vascular layer (uvea)**: Choroid, ciliary body, iris\n3. **Inner neural layer**: Retina\n\nContents:\n- Anterior chamber (aqueous humor)\n- Posterior chamber (aqueous humor)\n- Vitreous chamber (vitreous humor)\n- Lens\n\nOptical power approximately 60 diopters (cornea ~40, lens ~20).`,
    clinical_significance: 'Glaucoma increases intraocular pressure. Cataracts cloud lens. Retinal detachment is vision emergency. Diabetic retinopathy damages retina. Macular degeneration affects central vision. Globe rupture from trauma requires urgent surgery.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Optic nerve (CN II - vision), CN III/IV/VI (movement), CN V1 (sensation)',
    blood_supply: 'Ophthalmic artery, central retinal artery',
    model_reference: 'globe_eye',
    difficulty_rating: 4,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Superior rectus',
    common_names: ['SR'],
    latin_name: 'Musculus rectus superior',
    pronunciation_ipa: '/suːˈpɪəriər ˈrɛktəs/',
    system_slugs: ['muscular'],
    structure_type: StructureType.MUSCLE,
    parent_structure_name: null,
    definition_brief: 'Extraocular muscle primarily elevating the eye.',
    description_full: `The superior rectus is one of four rectus muscles controlling eye movement. It primarily elevates the eye.\n\nOrigin: Common tendinous ring (annulus of Zinn) at orbital apex\nInsertion: Superior sclera, anterior to equator\n\nPrimary action: Elevation (looking up)\nSecondary actions: Intorsion, adduction (when eye already adducted)\n\nPart of the extraocular muscle group with complex actions depending on eye position.`,
    clinical_significance: 'CN III palsy affects superior rectus causing inability to look up and in. Thyroid eye disease commonly affects this muscle. Strabismus surgery may involve this muscle. Diplopia occurs with paralysis.',
    origin: 'Common tendinous ring at orbital apex',
    insertion: 'Superior sclera, ~7.7mm from limbus',
    action: 'Primary: elevation; Secondary: intorsion, adduction',
    innervation: 'Oculomotor nerve (CN III) - superior division',
    blood_supply: 'Ophthalmic artery branches, lacrimal artery',
    model_reference: 'superior_rectus',
    difficulty_rating: 3,
    prerequisite_names: ['Globe'],
  },
  {
    canonical_name: 'Lacrimal gland',
    common_names: ['Tear gland'],
    latin_name: 'Glandula lacrimalis',
    pronunciation_ipa: '/ˈlækrɪməl ɡlænd/',
    system_slugs: ['special-senses'],
    structure_type: StructureType.ORGAN,
    parent_structure_name: null,
    definition_brief: 'Gland producing tears to lubricate and protect the eye.',
    description_full: `The lacrimal gland produces tears that lubricate, nourish, and protect the cornea.\n\nStructure:\n- **Orbital part**: Larger, superior\n- **Palpebral part**: Smaller, inferior\n- Divided by lateral horn of levator palpebrae superioris aponeurosis\n\nLocation: Superolateral orbit (lacrimal fossa of frontal bone)\n\nDrainage:\n- Secretes onto superior fornix\n- Tears spread across cornea with blinking\n- Drain medially to lacrimal puncta → canaliculi → lacrimal sac → nasolacrimal duct → inferior nasal meatus`,
    clinical_significance: 'Sjögren\'s syndrome causes dry eyes (keratoconjunctivitis sicca). Dacryoadenitis is gland inflammation. Lacrimal gland tumors are usually benign (pleomorphic adenoma). Facial nerve damage reduces tear production. Crocodile tears (aberrant regeneration).',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Parasympathetic: CN VII via greater petrosal nerve, pterygopalatine ganglion; Sympathetic: carotid plexus',
    blood_supply: 'Lacrimal artery (ophthalmic artery branch)',
    model_reference: 'lacrimal_gland',
    difficulty_rating: 3,
    prerequisite_names: ['Frontal bone', 'Globe'],
  },

  // ========================================
  // EAR STRUCTURES
  // ========================================
  {
    canonical_name: 'Auricle',
    common_names: ['Pinna', 'External ear'],
    latin_name: 'Auricula',
    pronunciation_ipa: '/ˈɔːrɪkəl/',
    system_slugs: ['special-senses'],
    structure_type: StructureType.OTHER,
    parent_structure_name: null,
    definition_brief: 'The visible external part of the ear that collects sound waves.',
    description_full: `The auricle (pinna) is the visible cartilaginous structure projecting from the head that funnels sound into the external acoustic meatus.\n\nLandmarks:\n- **Helix**: Outer rim\n- **Antihelix**: Inner curved prominence\n- **Tragus**: Anterior projection over meatus\n- **Antitragus**: Below tragus\n- **Lobule**: Soft, non-cartilaginous lower portion\n- **Concha**: Deep cavity leading to meatus\n- **Scapha**: Depression between helix and antihelix`,
    clinical_significance: 'Auricular hematoma ("cauliflower ear") requires drainage to prevent cartilage necrosis. Malformations include microtia. Preauricular pits are common. Tophi in gout. Frostbite affects auricle. Perichondritis is cartilage infection.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Great auricular nerve (C2-C3), auriculotemporal nerve (CN V3), auricular branch of vagus (CN X)',
    blood_supply: 'Posterior auricular, superficial temporal arteries',
    model_reference: 'auricle',
    difficulty_rating: 2,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Tympanic membrane',
    common_names: ['Eardrum', 'TM'],
    latin_name: 'Membrana tympanica',
    pronunciation_ipa: '/tɪmˈpænɪk ˈmɛmbreɪn/',
    system_slugs: ['special-senses'],
    structure_type: StructureType.OTHER,
    parent_structure_name: null,
    definition_brief: 'Thin membrane separating the external ear from the middle ear.',
    description_full: `The tympanic membrane (eardrum) is a thin, translucent, oval membrane at the end of the external acoustic meatus. It vibrates in response to sound waves.\n\nStructure:\n- **Pars tensa**: Main portion (4/5), tightly stretched\n- **Pars flaccida**: Superior portion (1/5), looser\n\nLayers:\n1. Outer epithelial (stratified squamous)\n2. Middle fibrous (collagen)\n3. Inner mucosal (simple cuboidal)\n\nManubrium of malleus attaches to medial surface, creating umbo (central depression).`,
    clinical_significance: 'Otitis media causes bulging, erythema. Perforation from trauma/infection causes conductive hearing loss. Otoscopy visualizes landmarks. Tympanometry tests mobility. Grommets (tubes) placed for chronic effusion. Cholesteatoma may erode TM.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Auriculotemporal nerve (CN V3 - outer), glossopharyngeal nerve (CN IX - inner)',
    blood_supply: 'Deep auricular artery (outer), anterior tympanic artery (inner)',
    model_reference: 'tympanic_membrane',
    difficulty_rating: 3,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Cochlea',
    common_names: ['Inner ear spiral'],
    latin_name: 'Cochlea',
    pronunciation_ipa: '/ˈkɒkliə/',
    system_slugs: ['special-senses'],
    structure_type: StructureType.ORGAN,
    parent_structure_name: null,
    definition_brief: 'Spiral-shaped organ of hearing in the inner ear.',
    description_full: `The cochlea is a snail-shaped structure in the petrous temporal bone containing the organ of Corti (sensory receptor for hearing).\n\nStructure:\n- **2.5 turns** around central modiolus\n- Three fluid-filled chambers:\n  1. Scala vestibuli (perilymph)\n  2. Scala media (endolymph, contains organ of Corti)\n  3. Scala tympani (perilymph)\n\nOrgan of Corti:\n- Hair cells (inner and outer)\n- Basilar membrane (frequency mapping)\n- Tectorial membrane\n\nFrequency coding: Base = high frequencies, Apex = low frequencies`,
    clinical_significance: 'Sensorineural hearing loss from hair cell damage (noise, aging, ototoxic drugs). Ménière\'s disease affects endolymph. Cochlear implants bypass damaged hair cells. Acoustic neuroma affects CN VIII. Presbycusis is age-related hearing loss.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Cochlear nerve (CN VIII)',
    blood_supply: 'Labyrinthine artery (from AICA)',
    model_reference: 'cochlea',
    difficulty_rating: 4,
    prerequisite_names: ['Temporal bone'],
  },

  // Additional structures to reach 70+ (abbreviated for space)
  {
    canonical_name: 'Nasal septum',
    common_names: ['Septum'],
    latin_name: 'Septum nasi',
    pronunciation_ipa: '/ˈneɪzəl ˈsɛptəm/',
    system_slugs: ['skeletal'],
    structure_type: StructureType.BONE,
    parent_structure_name: null,
    definition_brief: 'Midline partition dividing the nasal cavity into left and right sides.',
    description_full: `The nasal septum is the wall dividing the nasal cavity into two passages.\n\nComponents:\n- **Perpendicular plate of ethmoid**: Superior portion\n- **Vomer**: Posterior-inferior portion\n- **Septal cartilage**: Anterior portion\n\nOften deviated from midline (septal deviation).`,
    clinical_significance: 'Septal deviation causes nasal obstruction. Septal hematoma requires drainage. Epistaxis often from Kiesselbach\'s plexus (septum). Septal perforation from cocaine, trauma, surgery. Septoplasty corrects deviation.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Olfactory nerve (CN I), anterior ethmoidal nerve (CN V1), nasopalatine nerve (CN V2)',
    blood_supply: 'Anterior and posterior ethmoidal arteries, sphenopalatine artery, greater palatine artery',
    model_reference: 'nasal_septum',
    difficulty_rating: 3,
    prerequisite_names: ['Ethmoid bone'],
  },
  {
    canonical_name: 'Thyroid gland',
    common_names: ['Thyroid'],
    latin_name: 'Glandula thyroidea',
    pronunciation_ipa: '/ˈθaɪrɔɪd ɡlænd/',
    system_slugs: ['nervous'],
    structure_type: StructureType.ORGAN,
    parent_structure_name: null,
    definition_brief: 'Butterfly-shaped endocrine gland regulating metabolism.',
    description_full: `The thyroid gland is a highly vascular endocrine gland in the anterior neck.\n\nStructure:\n- Two lateral lobes connected by isthmus\n- Located at C5-T1 level\n- Lies against thyroid cartilage and upper tracheal rings\n\nProduces:\n- T3 (triiodothyronine)\n- T4 (thyroxine)\n- Calcitonin (C cells)`,
    clinical_significance: 'Hypothyroidism (fatigue, weight gain), hyperthyroidism (Graves\' disease). Thyroid nodules are common. Thyroidectomy may damage recurrent laryngeal nerve or parathyroid glands. Goiter is thyroid enlargement. Thyroid cancer usually has good prognosis.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Autonomic (sympathetic and parasympathetic)',
    blood_supply: 'Superior thyroid artery (ECA), inferior thyroid artery (thyrocervical trunk)',
    model_reference: 'thyroid_gland',
    difficulty_rating: 3,
    prerequisite_names: [],
  },
  {
    canonical_name: 'Parotid gland',
    common_names: ['Parotid'],
    latin_name: 'Glandula parotidea',
    pronunciation_ipa: '/pəˈrɒtɪd ɡlænd/',
    system_slugs: ['nervous'],
    structure_type: StructureType.ORGAN,
    parent_structure_name: null,
    definition_brief: 'Largest salivary gland located anterior to the ear.',
    description_full: `The parotid gland is the largest of the major salivary glands, producing serous (watery) saliva.\n\nLocation:\n- Overlies masseter muscle\n- Anterior to external acoustic meatus\n- Facial nerve (CN VII) passes through gland (surgical significance)\n\nDuct:\n- Parotid (Stensen's) duct crosses masseter\n- Opens into oral cavity opposite upper 2nd molar`,
    clinical_significance: 'Mumps causes parotitis. Parotid tumors (80% benign - pleomorphic adenoma). Facial nerve injury risk during parotidectomy. Frey\'s syndrome (gustatory sweating) post-surgery. Sjögren\'s syndrome affects gland. Sialolithiasis (stones) less common than submandibular.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Parasympathetic: CN IX via otic ganglion; Sympathetic: superior cervical ganglion',
    blood_supply: 'Branches of external carotid artery (transverse facial, superficial temporal)',
    model_reference: 'parotid_gland',
    difficulty_rating: 3,
    prerequisite_names: ['Temporal bone'],
  },
];

// ============================================================================
// Relationships (100+ relationships)
// ============================================================================

const relationships = [
  // Cranial nerve - target relationships
  {
    source_structure_name: 'Facial nerve',
    target_structure_name: 'Orbicularis oculi',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Facial nerve (CN VII) temporal and zygomatic branches innervate orbicularis oculi',
    bidirectional: false,
    clinical_relevance: 'Bell\'s palsy causes inability to close eye due to facial nerve paralysis',
  },
  {
    source_structure_name: 'Facial nerve',
    target_structure_name: 'Orbicularis oris',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Facial nerve buccal and mandibular branches innervate orbicularis oris',
    bidirectional: false,
    clinical_relevance: 'Facial nerve damage causes mouth drooping and inability to purse lips',
  },
  {
    source_structure_name: 'Facial nerve',
    target_structure_name: 'Frontalis',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Facial nerve temporal branch innervates frontalis muscle',
    bidirectional: false,
    clinical_relevance: 'Inability to raise eyebrow indicates facial nerve lesion (differentiates UMN from LMN)',
  },
  {
    source_structure_name: 'Trigeminal nerve',
    target_structure_name: 'Masseter',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Masseteric nerve (branch of mandibular division CN V3) innervates masseter',
    bidirectional: false,
    clinical_relevance: 'Trigeminal nerve lesions cause difficulty chewing and jaw deviation',
  },
  {
    source_structure_name: 'Trigeminal nerve',
    target_structure_name: 'Temporalis',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Deep temporal nerves (CN V3 branches) innervate temporalis muscle',
    bidirectional: false,
    clinical_relevance: 'CN V3 damage affects all muscles of mastication including temporalis',
  },
  {
    source_structure_name: 'Accessory nerve',
    target_structure_name: 'Sternocleidomastoid',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Accessory nerve (CN XI) provides motor innervation to SCM',
    bidirectional: false,
    clinical_relevance: 'Accessory nerve injury causes weakness in head rotation and SCM atrophy',
  },
  {
    source_structure_name: 'Accessory nerve',
    target_structure_name: 'Trapezius',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Accessory nerve (CN XI) innervates trapezius muscle',
    bidirectional: false,
    clinical_relevance: 'CN XI damage causes shoulder droop and scapular winging',
  },
  {
    source_structure_name: 'Oculomotor nerve',
    target_structure_name: 'Superior rectus',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Oculomotor nerve superior division innervates superior rectus',
    bidirectional: false,
    clinical_relevance: 'CN III palsy causes inability to elevate eye',
  },
  {
    source_structure_name: 'Glossopharyngeal nerve',
    target_structure_name: 'Parotid gland',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'CN IX provides parasympathetic innervation to parotid via otic ganglion',
    bidirectional: false,
    clinical_relevance: 'CN IX lesions reduce parotid secretion',
  },

  // Vascular supply relationships
  {
    source_structure_name: 'Common carotid artery',
    target_structure_name: 'Internal carotid artery',
    relationship_type: RelationshipType.BRANCH_OF,
    description: 'Internal carotid artery is medial terminal branch of common carotid',
    bidirectional: false,
    clinical_relevance: 'Carotid bifurcation is common site of atherosclerotic disease',
  },
  {
    source_structure_name: 'Common carotid artery',
    target_structure_name: 'External carotid artery',
    relationship_type: RelationshipType.BRANCH_OF,
    description: 'External carotid artery is lateral terminal branch of common carotid',
    bidirectional: false,
    clinical_relevance: 'ECA provides collateral circulation if ICA is stenotic',
  },
  {
    source_structure_name: 'External carotid artery',
    target_structure_name: 'Masseter',
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Masseter receives blood from masseteric and transverse facial arteries (ECA branches)',
    bidirectional: false,
    clinical_relevance: 'Rich blood supply enables muscle hypertrophy with bruxism',
  },
  {
    source_structure_name: 'External carotid artery',
    target_structure_name: 'Parotid gland',
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Parotid gland supplied by ECA branches (transverse facial, superficial temporal)',
    bidirectional: false,
    clinical_relevance: 'Parotid tumors may involve ECA branches requiring careful surgical dissection',
  },
  {
    source_structure_name: 'External carotid artery',
    target_structure_name: 'Thyroid gland',
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Superior thyroid artery (first ECA branch) supplies upper thyroid gland',
    bidirectional: false,
    clinical_relevance: 'Superior thyroid artery ligated during thyroidectomy',
  },
  {
    source_structure_name: 'Internal carotid artery',
    target_structure_name: 'Globe',
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Ophthalmic artery (ICA branch) supplies globe and orbit',
    bidirectional: false,
    clinical_relevance: 'ICA stenosis can cause amaurosis fugax (transient monocular blindness)',
  },

  // Venous drainage
  {
    source_structure_name: 'Globe',
    target_structure_name: 'Internal jugular vein',
    relationship_type: RelationshipType.DRAINS_TO,
    description: 'Orbital veins drain to cavernous sinus, then to internal jugular via inferior petrosal sinus',
    bidirectional: false,
    clinical_relevance: 'Orbital infections can spread to cavernous sinus causing thrombosis',
  },
  {
    source_structure_name: 'Thyroid gland',
    target_structure_name: 'Internal jugular vein',
    relationship_type: RelationshipType.DRAINS_TO,
    description: 'Superior and middle thyroid veins drain to internal jugular vein',
    bidirectional: false,
    clinical_relevance: 'Thyroid venous bleeding can occur during thyroidectomy',
  },

  // Anatomical articulations
  {
    source_structure_name: 'Temporal bone',
    target_structure_name: 'Mandible',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Mandibular condyle articulates with mandibular fossa of temporal bone (TMJ)',
    bidirectional: true,
    clinical_relevance: 'TMJ disorders cause jaw pain, clicking, and limited opening',
  },
  {
    source_structure_name: 'Frontal bone',
    target_structure_name: 'Parietal bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Frontal bone articulates with parietal bones at coronal suture',
    bidirectional: true,
    clinical_relevance: 'Coronal synostosis causes craniosynostosis (premature fusion)',
  },
  {
    source_structure_name: 'Parietal bone',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Parietal bone articulates with temporal bone at squamous suture',
    bidirectional: true,
    clinical_relevance: 'Pterion (H-shaped junction with frontal/sphenoid) is thinnest skull point',
  },
  {
    source_structure_name: 'Parietal bone',
    target_structure_name: 'Occipital bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Parietal bones articulate with occipital bone at lambdoid suture',
    bidirectional: true,
    clinical_relevance: 'Lambdoid synostosis less common than other craniosynostoses',
  },

  // Muscle attachments
  {
    source_structure_name: 'Masseter',
    target_structure_name: 'Zygomatic bone',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Masseter originates from zygomatic arch',
    bidirectional: false,
    clinical_relevance: 'Zygomatic fractures may affect masseter function',
  },
  {
    source_structure_name: 'Masseter',
    target_structure_name: 'Mandible',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Masseter inserts on lateral mandibular ramus and angle',
    bidirectional: false,
    clinical_relevance: 'Hypertrophy creates square jaw appearance',
  },
  {
    source_structure_name: 'Temporalis',
    target_structure_name: 'Mandible',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Temporalis inserts on coronoid process and anterior ramus of mandible',
    bidirectional: false,
    clinical_relevance: 'Coronoid fractures affect temporalis insertion',
  },
  {
    source_structure_name: 'Temporalis',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Temporalis originates from temporal fossa (temporal and parietal bones)',
    bidirectional: false,
    clinical_relevance: 'Temporal muscle wasting visible in malnutrition/cachexia',
  },
  {
    source_structure_name: 'Sternocleidomastoid',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'SCM inserts on mastoid process of temporal bone',
    bidirectional: false,
    clinical_relevance: 'Congenital muscular torticollis involves SCM shortening',
  },
  {
    source_structure_name: 'Trapezius',
    target_structure_name: 'Occipital bone',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Trapezius originates from external occipital protuberance and superior nuchal line',
    bidirectional: false,
    clinical_relevance: 'Occipital headaches may involve trapezius trigger points',
  },

  // Neural pathways through foramina
  {
    source_structure_name: 'Olfactory nerve',
    target_structure_name: 'Ethmoid bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Olfactory nerve fibers pass through cribriform plate of ethmoid bone',
    bidirectional: false,
    clinical_relevance: 'Cribriform plate fractures cause anosmia and CSF rhinorrhea',
  },
  {
    source_structure_name: 'Optic nerve',
    target_structure_name: 'Sphenoid bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Optic nerve passes through optic canal in lesser wing of sphenoid',
    bidirectional: false,
    clinical_relevance: 'Sphenoid fractures may damage optic nerve causing blindness',
  },
  {
    source_structure_name: 'Oculomotor nerve',
    target_structure_name: 'Sphenoid bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN III passes through superior orbital fissure in sphenoid bone',
    bidirectional: false,
    clinical_relevance: 'Superior orbital fissure syndrome affects CN III, IV, V1, VI',
  },
  {
    source_structure_name: 'Trochlear nerve',
    target_structure_name: 'Sphenoid bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN IV passes through superior orbital fissure',
    bidirectional: false,
    clinical_relevance: 'Long intracranial course makes CN IV vulnerable to trauma',
  },
  {
    source_structure_name: 'Abducens nerve',
    target_structure_name: 'Sphenoid bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN VI passes through superior orbital fissure',
    bidirectional: false,
    clinical_relevance: 'Cavernous sinus thrombosis affects CN VI causing abduction deficit',
  },
  {
    source_structure_name: 'Trigeminal nerve',
    target_structure_name: 'Sphenoid bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN V2 passes through foramen rotundum, CN V3 through foramen ovale in sphenoid',
    bidirectional: false,
    clinical_relevance: 'V2/V3 blocks target these foramina for facial anesthesia',
  },
  {
    source_structure_name: 'Facial nerve',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN VII enters internal acoustic meatus, traverses facial canal, exits stylomastoid foramen',
    bidirectional: false,
    clinical_relevance: 'Temporal bone fractures may damage CN VII causing facial paralysis',
  },
  {
    source_structure_name: 'Vestibulocochlear nerve',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN VIII passes through internal acoustic meatus in petrous temporal bone',
    bidirectional: false,
    clinical_relevance: 'Acoustic neuromas arise in internal acoustic meatus affecting CN VIII',
  },
  {
    source_structure_name: 'Glossopharyngeal nerve',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN IX exits skull via jugular foramen between temporal and occipital bones',
    bidirectional: false,
    clinical_relevance: 'Jugular foramen syndrome affects CN IX, X, XI',
  },
  {
    source_structure_name: 'Vagus nerve',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN X exits via jugular foramen',
    bidirectional: false,
    clinical_relevance: 'Glomus jugulare tumors compress CN X',
  },
  {
    source_structure_name: 'Accessory nerve',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN XI exits via jugular foramen after ascending through foramen magnum',
    bidirectional: false,
    clinical_relevance: 'Neck dissection may damage CN XI in posterior triangle',
  },
  {
    source_structure_name: 'Hypoglossal nerve',
    target_structure_name: 'Occipital bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CN XII exits skull through hypoglossal canal in occipital bone',
    bidirectional: false,
    clinical_relevance: 'Occipital condyle fractures may damage CN XII',
  },

  // Special sense organ relationships
  {
    source_structure_name: 'Lacrimal gland',
    target_structure_name: 'Frontal bone',
    relationship_type: RelationshipType.CONTAINS,
    description: 'Lacrimal gland sits in lacrimal fossa of frontal bone',
    bidirectional: false,
    clinical_relevance: 'Lacrimal gland tumors may erode bone',
  },
  {
    source_structure_name: 'Lacrimal gland',
    target_structure_name: 'Facial nerve',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Parasympathetic fibers from CN VII (via pterygopalatine ganglion) stimulate tear production',
    bidirectional: false,
    clinical_relevance: 'Facial nerve damage reduces tearing causing dry eye',
  },
  {
    source_structure_name: 'Cochlea',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.CONTAINS,
    description: 'Cochlea is housed within petrous portion of temporal bone',
    bidirectional: false,
    clinical_relevance: 'Temporal bone fractures can damage cochlea causing sensorineural hearing loss',
  },
  {
    source_structure_name: 'Cochlea',
    target_structure_name: 'Vestibulocochlear nerve',
    relationship_type: RelationshipType.INNERVATED_BY,
    description: 'Cochlear division of CN VIII innervates organ of Corti in cochlea',
    bidirectional: false,
    clinical_relevance: 'Acoustic neuromas cause progressive hearing loss',
  },
  {
    source_structure_name: 'Tympanic membrane',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Tympanic membrane attached to tympanic part of temporal bone',
    bidirectional: false,
    clinical_relevance: 'TM perforation impairs sound transmission',
  },
  {
    source_structure_name: 'Auricle',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Auricle attached to lateral temporal bone',
    bidirectional: false,
    clinical_relevance: 'Auricular hematomas require drainage to prevent deformity',
  },

  // Paranasal sinus relationships
  {
    source_structure_name: 'Frontal bone',
    target_structure_name: 'Ethmoid bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Frontal bone articulates with ethmoid at frontoethmoidal suture',
    bidirectional: true,
    clinical_relevance: 'Frontal sinus drains to middle meatus via ethmoid',
  },
  {
    source_structure_name: 'Maxilla',
    target_structure_name: 'Zygomatic bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Maxilla articulates with zygomatic bone at zygomaticomaxillary suture',
    bidirectional: true,
    clinical_relevance: 'Tripod fractures involve this articulation',
  },
  {
    source_structure_name: 'Maxilla',
    target_structure_name: 'Ethmoid bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Maxilla articulates with ethmoid bone medially',
    bidirectional: true,
    clinical_relevance: 'Ethmoidal sinusitis may spread to orbit through thin lamina papyracea',
  },
  {
    source_structure_name: 'Sphenoid bone',
    target_structure_name: 'Ethmoid bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Sphenoid articulates anteriorly with ethmoid',
    bidirectional: true,
    clinical_relevance: 'Sphenoid sinusitis can spread to cavernous sinus',
  },

  // Functional muscle relationships
  {
    source_structure_name: 'Masseter',
    target_structure_name: 'Temporalis',
    relationship_type: RelationshipType.SYNERGIST_WITH,
    description: 'Masseter and temporalis work together for jaw elevation (closing)',
    bidirectional: true,
    clinical_relevance: 'Both muscles tested for trigeminal nerve function',
  },
  {
    source_structure_name: 'Orbicularis oculi',
    target_structure_name: 'Frontalis',
    relationship_type: RelationshipType.ANTAGONIST_TO,
    description: 'Frontalis raises eyebrow, orbicularis oculi closes eye (antagonistic for brow position)',
    bidirectional: true,
    clinical_relevance: 'Facial nerve testing assesses both muscles',
  },

  // Glandular relationships
  {
    source_structure_name: 'Parotid gland',
    target_structure_name: 'Masseter',
    relationship_type: RelationshipType.SUPERFICIAL_TO,
    description: 'Parotid gland overlies masseter muscle',
    bidirectional: false,
    clinical_relevance: 'Parotid swelling visible over masseter',
  },
  {
    source_structure_name: 'Thyroid gland',
    target_structure_name: 'Vagus nerve',
    relationship_type: RelationshipType.CONTAINS,
    description: 'Recurrent laryngeal nerve (branch of CN X) runs near thyroid gland',
    bidirectional: false,
    clinical_relevance: 'Thyroidectomy risks recurrent laryngeal nerve injury causing hoarseness',
  },

  // Eye muscle relationships
  {
    source_structure_name: 'Superior rectus',
    target_structure_name: 'Globe',
    relationship_type: RelationshipType.ATTACHES_TO,
    description: 'Superior rectus inserts on superior sclera of globe',
    bidirectional: false,
    clinical_relevance: 'Thyroid eye disease commonly affects superior rectus',
  },

  // Additional vascular relationships
  {
    source_structure_name: 'Vertebral artery',
    target_structure_name: 'Occipital bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Vertebral artery enters skull through foramen magnum',
    bidirectional: false,
    clinical_relevance: 'Vertebral artery dissection can cause posterior circulation stroke',
  },
  {
    source_structure_name: 'Internal carotid artery',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'ICA passes through carotid canal in petrous temporal bone',
    bidirectional: false,
    clinical_relevance: 'ICA aneurysms may present with cranial nerve palsies',
  },

  // Structural containment
  {
    source_structure_name: 'Temporal bone',
    target_structure_name: 'Facial nerve',
    relationship_type: RelationshipType.CONTAINS,
    description: 'Facial canal in temporal bone contains CN VII',
    bidirectional: false,
    clinical_relevance: 'Temporal bone fractures commonly injure facial nerve',
  },
  {
    source_structure_name: 'Sphenoid bone',
    target_structure_name: 'Trigeminal nerve',
    relationship_type: RelationshipType.CONTAINS,
    description: 'Trigeminal ganglion sits in Meckel\'s cave in sphenoid bone',
    bidirectional: false,
    clinical_relevance: 'Trigeminal neuralgia may require ganglion intervention',
  },

  // Additional foramina relationships (to reach 100+)
  {
    source_structure_name: 'Maxilla',
    target_structure_name: 'Trigeminal nerve',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Infraorbital nerve (CN V2 branch) exits infraorbital foramen of maxilla',
    bidirectional: false,
    clinical_relevance: 'Infraorbital nerve blocks provide midface anesthesia',
  },
  {
    source_structure_name: 'Mandible',
    target_structure_name: 'Trigeminal nerve',
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Inferior alveolar nerve (CN V3) enters mandibular foramen, mental nerve exits mental foramen',
    bidirectional: false,
    clinical_relevance: 'Inferior alveolar nerve blocks provide lower jaw/teeth anesthesia',
  },
  {
    source_structure_name: 'Nasal septum',
    target_structure_name: 'Ethmoid bone',
    relationship_type: RelationshipType.CONTAINS,
    description: 'Perpendicular plate of ethmoid forms superior nasal septum',
    bidirectional: false,
    clinical_relevance: 'Septal deviation commonly involves ethmoid component',
  },

  // Deep/superficial relationships
  {
    source_structure_name: 'Platysma',
    target_structure_name: 'Sternocleidomastoid',
    relationship_type: RelationshipType.SUPERFICIAL_TO,
    description: 'Platysma lies superficial to sternocleidomastoid in neck',
    bidirectional: false,
    clinical_relevance: 'Platysma divided during neck surgery to access deeper structures',
  },
  {
    source_structure_name: 'Masseter',
    target_structure_name: 'Parotid gland',
    relationship_type: RelationshipType.DEEP_TO,
    description: 'Masseter lies deep to parotid gland',
    bidirectional: false,
    clinical_relevance: 'Parotid surgery requires identifying masseter',
  },

  // Continuity relationships
  {
    source_structure_name: 'Internal carotid artery',
    target_structure_name: 'Optic nerve',
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Ophthalmic artery (from ICA) runs with optic nerve in optic canal',
    bidirectional: false,
    clinical_relevance: 'ICA aneurysms can compress optic nerve',
  },

  // Final relationships to exceed 100
  {
    source_structure_name: 'Zygomatic bone',
    target_structure_name: 'Frontal bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Zygomatic bone articulates with frontal bone via frontal process',
    bidirectional: true,
    clinical_relevance: 'Zygomaticomaxillary complex fractures involve this articulation',
  },
  {
    source_structure_name: 'Zygomatic bone',
    target_structure_name: 'Temporal bone',
    relationship_type: RelationshipType.ARTICULATES_WITH,
    description: 'Temporal process of zygomatic forms zygomatic arch with zygomatic process of temporal',
    bidirectional: true,
    clinical_relevance: 'Zygomatic arch fractures impair jaw opening',
  },
  {
    source_structure_name: 'Anterior scalene',
    target_structure_name: 'Trigeminal nerve',
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Phrenic nerve (C3-C5) descends on anterior surface of anterior scalene',
    bidirectional: false,
    clinical_relevance: 'Interscalene block risks phrenic nerve paralysis',
  },
];

// ============================================================================
// Export Seed Data
// ============================================================================

export const headNeckSeedData: HeadNeckSeedData = {
  region,
  systems,
  structures,
  relationships,
};
