/**
 * Neuroanatomy Region Seed Data
 * Comprehensive anatomical data for the nervous system
 * Based on Netter's Atlas of Human Anatomy
 */

import {
  StructureType,
  RelationshipType,
  type Region,
  type System,
  type Structure,
  type Relationship,
} from '@/types';

// ============================================================================
// Region Definition
// ============================================================================

export const neuroanatomyRegion: Omit<Region, 'id'> = {
  name: 'Neuroanatomy',
  slug: 'neuroanatomy',
  description: 'Central and peripheral nervous systems including brain, spinal cord, and neural pathways',
  atlas_plate_range: '90-148',
  sort_order: 8,
  thumbnail_url: '/assets/regions/neuroanatomy.png',
};

// ============================================================================
// Systems
// ============================================================================

export const neuroanatomySystems: Omit<System, 'id'>[] = [
  {
    name: 'Central Nervous System',
    slug: 'central-nervous',
    description: 'Brain and spinal cord structures',
    color_code: '#6366F1', // Indigo
    sort_order: 1,
  },
  {
    name: 'Peripheral Nervous System',
    slug: 'peripheral-nervous',
    description: 'Cranial and spinal nerves, ganglia',
    color_code: '#8B5CF6', // Violet
    sort_order: 2,
  },
  {
    name: 'Autonomic Nervous System',
    slug: 'autonomic-nervous',
    description: 'Sympathetic and parasympathetic divisions',
    color_code: '#A855F7', // Purple
    sort_order: 3,
  },
];

// ============================================================================
// Structures (Minimum 60)
// ============================================================================

export const neuroanatomyStructures: Omit<Structure, 'id' | 'region_id' | 'system_ids' | 'created_at' | 'updated_at'>[] = [
  // ==========================================================================
  // CEREBRUM - Lobes and Major Gyri
  // ==========================================================================
  {
    canonical_name: 'Frontal Lobe',
    common_names: ['Frontal cortex'],
    latin_name: 'Lobus frontalis',
    pronunciation_ipa: '/ˈfrʌntəl loʊb/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Anterior portion of cerebral hemisphere responsible for executive function, motor control, and speech production.',
    description_full: `The frontal lobe is the largest lobe of the brain, extending from the frontal pole to the central sulcus. It contains the primary motor cortex (precentral gyrus), premotor areas, and prefrontal cortex.\n\nMajor gyri include: superior, middle, and inferior frontal gyri; precentral gyrus. Separated from parietal lobe by central sulcus and from temporal lobe by lateral sulcus.`,
    clinical_significance: 'Frontal lobe damage causes motor deficits, personality changes, executive dysfunction. Broca\'s area (inferior frontal gyrus, dominant hemisphere) lesions produce expressive aphasia. Frontal lobe tumors, strokes, and traumatic injury are common.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior cerebral artery (medial), middle cerebral artery (lateral)',
    model_reference: 'frontal_lobe',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Parietal Lobe',
    common_names: ['Parietal cortex'],
    latin_name: 'Lobus parietalis',
    pronunciation_ipa: '/pəˈraɪətəl loʊb/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Cerebral lobe processing somatosensory information and spatial awareness.',
    description_full: `Located between the central sulcus anteriorly and parieto-occipital sulcus posteriorly. Contains primary somatosensory cortex (postcentral gyrus) and association areas.\n\nMajor structures: postcentral gyrus, superior and inferior parietal lobules, supramarginal and angular gyri. Processes touch, proprioception, and spatial cognition.`,
    clinical_significance: 'Lesions cause contralateral sensory loss, apraxia, neglect syndrome, Gerstmann syndrome (angular gyrus). Dominant hemisphere damage affects reading, writing, calculation.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Middle cerebral artery (lateral), anterior cerebral artery (medial)',
    model_reference: 'parietal_lobe',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Temporal Lobe',
    common_names: ['Temporal cortex'],
    latin_name: 'Lobus temporalis',
    pronunciation_ipa: '/ˈtɛmpərəl loʊb/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Lateral cerebral lobe responsible for auditory processing, language comprehension, and memory.',
    description_full: `Located inferior to lateral sulcus, extending to temporal pole. Contains primary auditory cortex (Heschl's gyrus), auditory association areas, and medial temporal lobe memory structures.\n\nMajor gyri: superior, middle, inferior temporal gyri. Deep structures include hippocampus, amygdala, and parahippocampal gyrus.`,
    clinical_significance: 'Wernicke\'s area (superior temporal gyrus, dominant hemisphere) damage causes receptive aphasia. Bilateral medial temporal damage (including hippocampus) produces severe anterograde amnesia. Temporal lobe epilepsy is common.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Middle cerebral artery (lateral), posterior cerebral artery (inferior/medial)',
    model_reference: 'temporal_lobe',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Occipital Lobe',
    common_names: ['Occipital cortex', 'Visual cortex'],
    latin_name: 'Lobus occipitalis',
    pronunciation_ipa: '/ɑkˈsɪpɪtəl loʊb/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Posterior cerebral lobe dedicated to visual processing.',
    description_full: `The smallest cerebral lobe, located posterior to parieto-occipital sulcus. Contains primary visual cortex (V1, striate cortex, Brodmann area 17) along calcarine sulcus and visual association areas.\n\nMedial surface features calcarine sulcus dividing cuneus (superior) and lingual gyrus (inferior). Lateral surface has lateral occipital gyri.`,
    clinical_significance: 'Unilateral damage causes contralateral homonymous hemianopia. Bilateral damage produces cortical blindness. Calcarine artery occlusion causes macular-sparing hemianopia. Anton syndrome (cortical blindness with anosognosia) occurs with bilateral lesions.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery (primary), middle cerebral artery (small lateral portion)',
    model_reference: 'occipital_lobe',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Precentral Gyrus',
    common_names: ['Primary motor cortex', 'Motor strip', 'M1'],
    latin_name: 'Gyrus praecentralis',
    pronunciation_ipa: '/priːˈsɛntrəl ˈdʒaɪrəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Primary motor cortex located anterior to central sulcus, controlling voluntary movement.',
    description_full: `Brodmann area 4, immediately anterior to central sulcus in frontal lobe. Contains upper motor neurons (Betz cells) whose axons form corticospinal and corticobulbar tracts.\n\nSomatotopically organized as motor homunculus: lower limb medial (superior), upper limb lateral, face most lateral. Disproportionate representation reflects fine motor control (hand, face larger than trunk).`,
    clinical_significance: 'Lesions produce contralateral weakness or paralysis. Upper motor neuron pattern: increased tone, hyperreflexia, Babinski sign. MCA stroke commonly affects face/arm more than leg. ACA stroke affects leg more than face/arm.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior cerebral artery (medial), middle cerebral artery (lateral)',
    model_reference: 'precentral_gyrus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Postcentral Gyrus',
    common_names: ['Primary somatosensory cortex', 'Sensory strip', 'S1'],
    latin_name: 'Gyrus postcentralis',
    pronunciation_ipa: '/poʊstˈsɛntrəl ˈdʒaɪrəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Primary somatosensory cortex located posterior to central sulcus, processing tactile and proprioceptive information.',
    description_full: `Brodmann areas 3, 1, 2, immediately posterior to central sulcus in parietal lobe. Receives somatosensory input from thalamus (VPL and VPM nuclei) via thalamocortical radiations.\n\nSomatotopically organized as sensory homunculus, mirror image of motor homunculus. Area 3 receives direct thalamic input, areas 1 and 2 process texture and shape.`,
    clinical_significance: 'Lesions cause contralateral sensory loss (touch, proprioception, vibration). Sensory neglect may occur with parietal lesions. Thalamic pain syndrome can develop. Loss of two-point discrimination, stereognosis, graphesthesia.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior cerebral artery (medial), middle cerebral artery (lateral)',
    model_reference: 'postcentral_gyrus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // BASAL GANGLIA
  // ==========================================================================
  {
    canonical_name: 'Caudate Nucleus',
    common_names: ['Caudate'],
    latin_name: 'Nucleus caudatus',
    pronunciation_ipa: '/ˈkɔːdeɪt ˈnuːkliəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'C-shaped basal ganglia structure with head, body, and tail, involved in motor control and cognition.',
    description_full: `Major component of striatum (with putamen). C-shaped structure following lateral ventricle: large head bulging into anterior horn, slender body along lateral ventricle, tail ending at amygdala.\n\nReceives cortical input (especially from frontal and parietal lobes) and projects to globus pallidus. Part of direct and indirect motor pathways.`,
    clinical_significance: 'Atrophy in Huntington\'s disease (genetic CAG repeat expansion). Involved in obsessive-compulsive disorder. Hemorrhage in caudate causes movement disorders and cognitive changes. Part of basal ganglia circuitry affected in Parkinson\'s disease.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Lateral striate arteries (lenticulostriate, branches of MCA), anterior cerebral artery',
    model_reference: 'caudate_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Putamen',
    common_names: [],
    latin_name: 'Putamen',
    pronunciation_ipa: '/pjuːˈteɪmən/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Lateral component of lentiform nucleus and striatum, involved in motor learning and execution.',
    description_full: `Forms lateral part of lentiform nucleus (with globus pallidus medial). Together with caudate forms striatum (functionally unified despite being separated by internal capsule).\n\nLargest component of basal ganglia. Receives massive cortical input and projects to globus pallidus. Critical for motor programming and procedural learning.`,
    clinical_significance: 'Lacunar infarcts cause pure motor hemiparesis. Putaminal hemorrhage is most common type of basal ganglia hemorrhage (hypertension). Involved in Parkinson\'s disease, Huntington\'s disease, dystonia. Calcification in Fahr\'s disease.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Lateral striate arteries (lenticulostriate branches of MCA)',
    model_reference: 'putamen',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Globus Pallidus',
    common_names: ['Pallidum', 'Pale globe'],
    latin_name: 'Globus pallidus',
    pronunciation_ipa: '/ˈɡloʊbəs ˈpælɪdəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Medial component of lentiform nucleus with internal and external segments, regulating movement via thalamic projections.',
    description_full: `Forms medial portion of lentiform nucleus. Divided into external (GPe) and internal (GPi) segments by medial medullary lamina. Pale appearance (high myelin content) contrasts with darker putamen.\n\nGPe participates in indirect pathway (inhibitory). GPi is major basal ganglia output nucleus, projecting to thalamus (VL/VA nuclei). Critical for movement regulation and suppression of unwanted movements.`,
    clinical_significance: 'Bilateral necrosis in carbon monoxide poisoning, kernicterus. Target for deep brain stimulation in Parkinson\'s disease. Involved in dystonia pathophysiology. Part of circuits affected in Wilson\'s disease.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior choroidal artery, lateral striate arteries',
    model_reference: 'globus_pallidus',
    image_references: [],
    difficulty_rating: 5,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Substantia Nigra',
    common_names: ['Black substance'],
    latin_name: 'Substantia nigra',
    pronunciation_ipa: '/səbˈstænʃə ˈnaɪɡrə/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Midbrain structure with dopaminergic neurons projecting to striatum, critical for movement control.',
    description_full: `Located in midbrain tegmentum. Divided into pars compacta (dorsal, densely packed dopaminergic neurons with neuromelanin) and pars reticulata (ventral, GABAergic neurons continuous with GPi).\n\nPars compacta projects to striatum via nigrostriatal pathway, modulating striatal activity. Forms part of basal ganglia circuitry despite anatomic location in brainstem.`,
    clinical_significance: 'Degeneration of dopaminergic neurons in pars compacta causes Parkinson\'s disease (bradykinesia, rigidity, tremor, postural instability). Loss of neuromelanin visible on MRI. Target for MPTP toxicity, LRRK2/SNCA mutations. Lewy bodies are pathologic hallmark.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of posterior cerebral artery, superior cerebellar artery, basilar artery perforators',
    model_reference: 'substantia_nigra',
    image_references: [],
    difficulty_rating: 5,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Subthalamic Nucleus',
    common_names: ['Nucleus of Luys'],
    latin_name: 'Nucleus subthalamicus',
    pronunciation_ipa: '/sʌbθəˈlæmɪk ˈnuːkliəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Lens-shaped nucleus in subthalamus providing excitatory drive to basal ganglia output.',
    description_full: `Small, lens-shaped nucleus in ventral thalamus/subthalamus. Receives input from GPe and motor cortex. Projects to GPi/SNr, providing excitatory (glutamatergic) drive.\n\nCritical node in indirect pathway. Balances direct and indirect pathways to regulate movement. Only excitatory component of basal ganglia circuitry.`,
    clinical_significance: 'Lesions cause contralateral hemiballismus (violent flinging movements, especially proximal limbs). Primary target for deep brain stimulation in Parkinson\'s disease (most effective site). Involved in dystonia, obsessive-compulsive disorder.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior communicating artery, posterior cerebral artery, anterior choroidal artery',
    model_reference: 'subthalamic_nucleus',
    image_references: [],
    difficulty_rating: 5,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // THALAMUS & HYPOTHALAMUS
  // ==========================================================================
  {
    canonical_name: 'Thalamus',
    common_names: ['Dorsal thalamus'],
    latin_name: 'Thalamus',
    pronunciation_ipa: '/ˈθæləməs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Paired egg-shaped diencephalic structure serving as relay station for sensory and motor information.',
    description_full: `Large paired nuclear complex forming lateral walls of third ventricle. Composed of multiple functionally distinct nuclei organized into anterior, medial, lateral, and posterior groups.\n\nKey relay nuclei: VPL/VPM (somatosensory), LGN (visual), MGN (auditory), VL/VA (motor). Association nuclei connect to association cortex. Intralaminar nuclei project diffusely. Reticular nucleus modulates thalamic activity.`,
    clinical_significance: 'Thalamic stroke causes contralateral sensory loss (lacunar: pure sensory). Posterior circulation strokes cause thalamic pain syndrome (Dejerine-Roussy). Thalamic hemorrhage produces sensory loss, hemianopia, miosis. Fatal familial insomnia affects thalamus.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery, posterior communicating artery, basilar artery perforators, anterior choroidal artery',
    model_reference: 'thalamus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Hypothalamus',
    common_names: [],
    latin_name: 'Hypothalamus',
    pronunciation_ipa: '/ˌhaɪpoʊˈθæləməs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Ventral diencephalic structure regulating autonomic function, endocrine system, and homeostasis.',
    description_full: `Small region forming floor and inferior lateral walls of third ventricle. Contains numerous nuclei regulating vital functions: temperature, hunger/satiety, thirst, circadian rhythms, sexual behavior.\n\nMajor nuclei: supraoptic and paraventricular (ADH, oxytocin), suprachiasmatic (circadian), arcuate (feeding), ventromedial (satiety), lateral (hunger), preoptic (temperature), mammillary bodies (memory).`,
    clinical_significance: 'Lesions cause diabetes insipidus, SIADH, temperature dysregulation, obesity/wasting, precocious puberty, loss of circadian rhythm. Craniopharyngioma commonly affects hypothalamus. Wernicke-Korsakoff syndrome affects mammillary bodies.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Circle of Willis branches, posterior communicating artery, anterior cerebral artery, superior hypophyseal arteries',
    model_reference: 'hypothalamus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // LIMBIC SYSTEM
  // ==========================================================================
  {
    canonical_name: 'Hippocampus',
    common_names: ['Hippocampal formation'],
    latin_name: 'Hippocampus',
    pronunciation_ipa: '/ˌhɪpəˈkæmpəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Seahorse-shaped medial temporal lobe structure critical for declarative memory formation.',
    description_full: `Curved structure in medial temporal lobe, part of limbic system. Consists of dentate gyrus, CA fields (CA1-CA4), and subiculum. Connected to mammillary bodies via fornix.\n\nReceives highly processed sensory information from entorhinal cortex. CA1 is vulnerable to hypoxia. Neurogenesis occurs in dentate gyrus. Critical for memory consolidation (conversion of short-term to long-term memory).`,
    clinical_significance: 'Bilateral damage causes severe anterograde amnesia (patient H.M.). Alzheimer\'s disease affects hippocampus early. Temporal lobe epilepsy commonly involves hippocampal sclerosis. Transient global amnesia. Hypoxic-ischemic injury (CA1 most vulnerable).',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior choroidal artery, posterior cerebral artery (temporal branches)',
    model_reference: 'hippocampus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Amygdala',
    common_names: ['Amygdaloid complex', 'Amygdaloid body'],
    latin_name: 'Corpus amygdaloideum',
    pronunciation_ipa: '/əˈmɪɡdələ/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Almond-shaped limbic structure processing emotions, particularly fear and threat detection.',
    description_full: `Located anterior to hippocampus in medial temporal lobe. Collection of nuclei (basolateral, corticomedial, central groups). Extensive connections to cortex, thalamus, hypothalamus, and brainstem.\n\nCentral to fear conditioning, emotional learning, and memory modulation. Evaluates emotional significance of stimuli. Projects to hypothalamus and brainstem for autonomic/behavioral responses.`,
    clinical_significance: 'Bilateral lesions (Klüver-Bucy syndrome) cause hyperorality, hypersexuality, placidity, visual agnosia. Hyperactivity in anxiety disorders, PTSD. Involved in autism spectrum disorders. Seizures from amygdala cause fear/anxiety sensations.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior choroidal artery, middle cerebral artery branches',
    model_reference: 'amygdala',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Fornix',
    common_names: ['Fornix cerebri'],
    latin_name: 'Fornix',
    pronunciation_ipa: '/ˈfɔːrnɪks/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'C-shaped white matter tract connecting hippocampus to mammillary bodies and septal nuclei.',
    description_full: `Major output pathway from hippocampus. Arises from hippocampus/subiculum as fimbria, becomes crus of fornix, joins contralateral side to form body, then splits into columns that descend to mammillary bodies and septal area.\n\nPart of Papez circuit (hippocampus → fornix → mammillary bodies → anterior thalamus → cingulate → entorhinal cortex → hippocampus). Critical for memory processing.`,
    clinical_significance: 'Bilateral damage causes anterograde amnesia. Colloid cysts of third ventricle can compress fornix. Surgical damage during neurosurgery causes memory deficits. Part of circuit affected in Wernicke-Korsakoff syndrome.',
    origin: 'Hippocampus, subiculum',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior cerebral artery, posterior cerebral artery',
    model_reference: 'fornix',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Cingulate Gyrus',
    common_names: ['Cingulate cortex'],
    latin_name: 'Gyrus cinguli',
    pronunciation_ipa: '/ˈsɪŋɡjələt ˈdʒaɪrəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Curved gyrus on medial surface of hemisphere, part of limbic system involved in emotion and pain processing.',
    description_full: `Arches around corpus callosum on medial hemispheric surface. Divided into anterior (executive function, conflict monitoring), middle (motor), and posterior (memory, spatial orientation) portions.\n\nAnterior cingulate cortex (ACC) involved in error detection, conflict monitoring, pain processing. Posterior cingulate cortex (PCC) part of default mode network. Part of Papez circuit for emotion/memory.`,
    clinical_significance: 'Anterior cingulate lesions cause akinetic mutism, apathy. Cingulotomy performed for intractable pain, OCD. Involved in depression, chronic pain syndromes. Posterior cingulate affected early in Alzheimer\'s disease.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior cerebral artery (pericallosal and callosomarginal branches)',
    model_reference: 'cingulate_gyrus',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // CEREBELLUM
  // ==========================================================================
  {
    canonical_name: 'Cerebellum',
    common_names: ['Little brain'],
    latin_name: 'Cerebellum',
    pronunciation_ipa: '/ˌsɛrəˈbɛləm/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Posterior fossa structure responsible for motor coordination, balance, and motor learning.',
    description_full: `Located in posterior fossa, inferior to occipital lobes. Divided into vermis (midline) and hemispheres (lateral). Three lobes: anterior, posterior, flocculonodular.\n\nFunctional divisions: vestibulocerebellum (flocculonodular, balance), spinocerebellum (vermis/paravermis, posture/gait), cerebrocerebellum (hemispheres, motor planning). Contains more neurons than cerebral cortex.`,
    clinical_significance: 'Lesions cause ipsilateral ataxia, dysmetria, dysdiadochokinesia, intention tremor, nystagmus, dysarthria. Alcohol toxicity preferentially affects anterior vermis (gait ataxia). Stroke, tumor, multiple sclerosis, hereditary ataxias (SCAs), paraneoplastic syndromes.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior inferior cerebellar artery (PICA), anterior inferior cerebellar artery (AICA), superior cerebellar artery (SCA)',
    model_reference: 'cerebellum',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Dentate Nucleus',
    common_names: ['Nucleus dentatus'],
    latin_name: 'Nucleus dentatus',
    pronunciation_ipa: '/ˈdɛnteɪt ˈnuːkliəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Largest and most lateral deep cerebellar nucleus, projecting to motor cortex via thalamus.',
    description_full: `Largest deep cerebellar nucleus, located in lateral cerebellar hemisphere. Distinctive serrated appearance on cross-section. Receives input from cerebellar cortex (Purkinje cells) and sends output via superior cerebellar peduncle.\n\nProjects to contralateral red nucleus and VL/VA thalamus (which project to motor cortex). Part of cerebrocerebellum circuit for motor planning and coordination.`,
    clinical_significance: 'Lesions cause intention tremor, dysmetria, dysarthria. Involved in essential tremor pathophysiology. Target for deep brain stimulation in tremor disorders. Hypertrophic olivary degeneration can occur with dentate damage.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Superior cerebellar artery',
    model_reference: 'dentate_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // BRAINSTEM - Midbrain
  // ==========================================================================
  {
    canonical_name: 'Midbrain',
    common_names: ['Mesencephalon'],
    latin_name: 'Mesencephalon',
    pronunciation_ipa: '/ˈmɛsɛnˌsɛfəlɒn/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Superior portion of brainstem connecting pons to diencephalon, containing cranial nerve nuclei III and IV.',
    description_full: `Shortest brainstem segment, connecting pons to thalamus. Divided into tectum (dorsal, superior and inferior colliculi), tegmentum (middle), and crus cerebri/cerebral peduncles (ventral).\n\nContains cranial nerve nuclei (CN III, IV), substantia nigra, red nucleus, periaqueductal gray, reticular formation. Cerebral aqueduct connects third and fourth ventricles.`,
    clinical_significance: 'Midbrain stroke causes various syndromes: Weber (CN III palsy + contralateral hemiplegia), Benedikt (CN III + ataxia/tremor), Claude (CN III + ataxia), Parinaud (upgaze palsy). Compression causes Cushing reflex. Pineal tumors compress tectum.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery, superior cerebellar artery, basilar artery perforators',
    model_reference: 'midbrain',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Pons',
    common_names: ['Pons Varolii'],
    latin_name: 'Pons',
    pronunciation_ipa: '/pɒnz/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Middle brainstem segment containing cranial nerve nuclei V-VIII and connecting pathways.',
    description_full: `Located between midbrain and medulla. Divided into basilar pons (ventral, with transverse fibers and descending tracts) and pontine tegmentum (dorsal, with cranial nerve nuclei and ascending tracts).\n\nContains CN nuclei (V motor/sensory, VI, VII, VIII). Middle cerebellar peduncles connect pons to cerebellum. Pneumotaxic center regulates breathing. Fourth ventricle forms posterior border.`,
    clinical_significance: 'Pontine stroke causes locked-in syndrome (ventral), facial paralysis (CN VII), lateral gaze palsy (CN VI). Multiple sclerosis commonly affects pons. Central pontine myelinolysis from rapid sodium correction. Pontine gliomas in children.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Basilar artery and branches (paramedian, short circumferential, long circumferential)',
    model_reference: 'pons',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Medulla Oblongata',
    common_names: ['Medulla', 'Myelencephalon'],
    latin_name: 'Medulla oblongata',
    pronunciation_ipa: '/məˈdʌlə ˌɒblɒŋˈɡɑːtə/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Most caudal brainstem segment containing vital cardiorespiratory centers and cranial nerve nuclei IX-XII.',
    description_full: `Inferior brainstem, continuous with spinal cord at foramen magnum. Anterior surface: pyramids (corticospinal tracts), olives (inferior olivary nuclei). Posterior surface: gracile and cuneate tubercles (dorsal column nuclei).\n\nContains vital centers (respiratory, cardiac, vasomotor), cranial nerve nuclei (IX-XII). Pyramidal decussation at medullary-spinal junction. Fourth ventricle forms posterior boundary.`,
    clinical_significance: 'Lateral medullary syndrome/Wallenberg (PICA): vertigo, ataxia, dysphagia, Horner syndrome, sensory loss. Medial medullary syndrome: tongue deviation, contralateral weakness/sensory loss. Respiratory/cardiac arrest with lesions. Syringobulbia, Chiari malformation.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Vertebral artery, anterior spinal artery, posterior inferior cerebellar artery (PICA)',
    model_reference: 'medulla_oblongata',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // VENTRICULAR SYSTEM
  // ==========================================================================
  {
    canonical_name: 'Lateral Ventricles',
    common_names: ['First and second ventricles'],
    latin_name: 'Ventriculi laterales',
    pronunciation_ipa: '/ˈlætərəl ˈvɛntrɪkəlz/',
    structure_type: StructureType.OTHER,
    parent_structure_id: null,
    definition_brief: 'Paired C-shaped CSF-filled cavities within cerebral hemispheres.',
    description_full: `Largest ventricles, one in each hemisphere. Each has anterior horn (frontal), body (parietal), posterior horn (occipital), and inferior horn (temporal). Connect to third ventricle via interventricular foramina of Monro.\n\nContain choroid plexus producing CSF. Lined by ependymal cells. Caudate nucleus and thalamus form walls. Expand in hydrocephalus, cerebral atrophy.`,
    clinical_significance: 'Enlarged in hydrocephalus, normal pressure hydrocephalus, cerebral atrophy. Colloid cysts at foramen of Monro cause acute hydrocephalus. Intraventricular hemorrhage in premature infants. Shunts placed in lateral ventricle for hydrocephalus.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Choroid plexus supplied by anterior and posterior choroidal arteries',
    model_reference: 'lateral_ventricles',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Third Ventricle',
    common_names: [],
    latin_name: 'Ventriculus tertius',
    pronunciation_ipa: '/θɜːrd ˈvɛntrɪkəl/',
    structure_type: StructureType.OTHER,
    parent_structure_id: null,
    definition_brief: 'Midline CSF-filled cavity between thalami, connecting lateral ventricles to fourth ventricle.',
    description_full: `Narrow midline cleft between thalami. Bounded by hypothalamus inferiorly, thalamus laterally. Optic and infundibular recesses anteroinferiorly, pineal and suprapineal recesses posteriorly.\n\nCommunicates with lateral ventricles via foramina of Monro, with fourth ventricle via cerebral aqueduct. Contains choroid plexus in roof.`,
    clinical_significance: 'Colloid cysts cause obstructive hydrocephalus. Pineal tumors compress posterior third ventricle. Third ventriculostomy creates alternate CSF pathway. Massa intermedia (interthalamic adhesion) crosses ventricle.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior choroidal arteries supply choroid plexus',
    model_reference: 'third_ventricle',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Cerebral Aqueduct',
    common_names: ['Aqueduct of Sylvius', 'Mesencephalic aqueduct'],
    latin_name: 'Aqueductus cerebri',
    pronunciation_ipa: '/səˈriːbrəl ˈækwɪdʌkt/',
    structure_type: StructureType.OTHER,
    parent_structure_id: null,
    definition_brief: 'Narrow channel through midbrain connecting third and fourth ventricles.',
    description_full: `Narrow tube traversing midbrain, approximately 15mm long. Surrounded by periaqueductal gray matter. Smallest part of ventricular system, making it vulnerable to obstruction.\n\nNo choroid plexus. CSF flows from third ventricle through aqueduct to fourth ventricle. Stenosis is congenital or acquired.`,
    clinical_significance: 'Aqueductal stenosis causes non-communicating hydrocephalus. Can be congenital (X-linked) or acquired (infection, tumor, hemorrhage). Compression from pineal tumors, tectal gliomas. Endoscopic third ventriculostomy bypasses obstruction.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery and basilar artery perforators',
    model_reference: 'cerebral_aqueduct',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Fourth Ventricle',
    common_names: [],
    latin_name: 'Ventriculus quartus',
    pronunciation_ipa: '/fɔːrθ ˈvɛntrɪkəl/',
    structure_type: StructureType.OTHER,
    parent_structure_id: null,
    definition_brief: 'Tent-shaped CSF cavity between cerebellum and brainstem, connecting to subarachnoid space.',
    description_full: `Diamond-shaped cavity between pons/medulla (floor) and cerebellum (roof). Floor forms rhomboid fossa with important brainstem nuclei landmarks.\n\nCommunicates with cerebral aqueduct superiorly, central canal of spinal cord inferiorly. CSF exits via foramina of Luschka (lateral) and Magendie (median) into subarachnoid space. Contains choroid plexus in roof.`,
    clinical_significance: 'Posterior fossa tumors (medulloblastoma, ependymoma) obstruct fourth ventricle causing hydrocephalus. Dandy-Walker malformation (absent/hypoplastic cerebellar vermis, cystic fourth ventricle). Chiari malformations affect CSF flow.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior inferior cerebellar artery (PICA), anterior inferior cerebellar artery (AICA)',
    model_reference: 'fourth_ventricle',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // SPINAL CORD - Segments and Tracts
  // ==========================================================================
  {
    canonical_name: 'Spinal Cord',
    common_names: ['Medulla spinalis'],
    latin_name: 'Medulla spinalis',
    pronunciation_ipa: '/ˈspaɪnəl kɔːrd/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Cylindrical neural structure extending from medulla to conus medullaris, transmitting signals and mediating reflexes.',
    description_full: `Extends from foramen magnum (medullary-spinal junction) to L1-L2 vertebral level (conus medullaris). Cervical and lumbar enlargements for limb innervation. Central gray matter (butterfly-shaped) surrounded by white matter tracts.\n\nGray matter: dorsal horn (sensory), lateral horn (autonomic, T1-L2), ventral horn (motor). White matter: dorsal columns, lateral columns, ventral columns. Cauda equina below conus.`,
    clinical_significance: 'Spinal cord injury causes quadriplegia (cervical) or paraplegia (thoracic/lumbar). Complete vs incomplete syndromes. Central cord syndrome, Brown-Séquard, anterior cord syndrome. Multiple sclerosis, ALS, syringomyelia, epidural hematoma, cord compression.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior spinal artery (anterior 2/3), paired posterior spinal arteries (posterior 1/3), segmental radicular arteries',
    model_reference: 'spinal_cord',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Lateral Corticospinal Tract',
    common_names: ['Crossed pyramidal tract'],
    latin_name: 'Tractus corticospinalis lateralis',
    pronunciation_ipa: '/ˈlætərəl ˌkɔːrtɪkoʊˈspaɪnəl trækt/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Major descending motor pathway controlling voluntary movement of limbs and trunk.',
    description_full: `Carries upper motor neuron axons from motor cortex (primarily precentral gyrus) to spinal cord. Descends through internal capsule, cerebral peduncle, pons, pyramids of medulla. 85-90% of fibers decussate at pyramidal decussation.\n\nDescends in lateral white column. Synapses on alpha motor neurons in ventral horn (lower motor neurons). Controls fine voluntary movements, especially distal limbs.`,
    clinical_significance: 'Upper motor neuron lesions above decussation cause contralateral weakness (increased tone, hyperreflexia, Babinski sign). Lesions below decussation cause ipsilateral weakness. Stroke, ALS, spinal cord injury, Brown-Séquard syndrome (ipsilateral weakness below lesion).',
    origin: 'Primary motor cortex (precentral gyrus), premotor cortex, supplementary motor area',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior spinal artery in spinal cord',
    model_reference: 'lateral_corticospinal_tract',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Spinothalamic Tract',
    common_names: ['Anterolateral system'],
    latin_name: 'Tractus spinothalamicus',
    pronunciation_ipa: '/ˌspaɪnoʊθəˈlæmɪk trækt/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Ascending sensory pathway transmitting pain and temperature from body to thalamus.',
    description_full: `Transmits pain and temperature sensation. First-order neurons in dorsal root ganglia synapse in dorsal horn (substantia gelatinosa). Second-order neurons decussate within 1-2 segments via anterior white commissure, then ascend in lateral white column.\n\nLateral spinothalamic tract (pain/temperature) more lateral, anterior spinothalamic tract (crude touch) more anterior. Terminates in VPL nucleus of thalamus. Somatotopically organized (cervical medial, lumbar lateral).`,
    clinical_significance: 'Lesions cause contralateral loss of pain/temperature 1-2 segments below lesion. Brown-Séquard syndrome (contralateral pain/temp loss). Syringomyelia disrupts crossing fibers (bilateral loss at level). Cordotomy for intractable pain. Central cord syndrome spares spinothalamic tract.',
    origin: 'Dorsal horn neurons (substantia gelatinosa)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior spinal artery',
    model_reference: 'spinothalamic_tract',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Dorsal Column-Medial Lemniscus Pathway',
    common_names: ['Posterior column pathway', 'DCML'],
    latin_name: 'Fasciculus gracilis et cuneatus',
    pronunciation_ipa: '/ˈdɔːrsəl ˈkɒləm ˈmidiəl lɛmˈnɪskəs/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Ascending pathway transmitting fine touch, vibration, and proprioception.',
    description_full: `Transmits discriminative touch, vibration, proprioception. First-order neurons ascend ipsilaterally in dorsal columns: fasciculus gracilis (lower body/leg, medial) and fasciculus cuneatus (upper body/arm, lateral).\n\nSynapse in gracile and cuneate nuclei in medulla. Second-order neurons decussate as internal arcuate fibers, form medial lemniscus, ascend to VPL thalamus. Third-order neurons project to postcentral gyrus.`,
    clinical_significance: 'Lesions cause ipsilateral loss of vibration, proprioception, fine touch below lesion. Positive Romberg sign. Tabes dorsalis (neurosyphilis) affects dorsal columns. Vitamin B12 deficiency (subacute combined degeneration). Multiple sclerosis. Brown-Séquard syndrome.',
    origin: 'Dorsal root ganglia',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior spinal arteries',
    model_reference: 'dorsal_column_pathway',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Spinocerebellar Tracts',
    common_names: ['Dorsal and ventral spinocerebellar'],
    latin_name: 'Tractus spinocerebellaris',
    pronunciation_ipa: '/ˌspaɪnoʊˌsɛrəˈbɛlər trækts/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Ascending pathways carrying unconscious proprioception from muscles and joints to cerebellum.',
    description_full: `Dorsal spinocerebellar tract (DSCT): originates in Clarke's nucleus (C8-L2), ascends ipsilaterally in lateral column, enters cerebellum via inferior cerebellar peduncle. Transmits proprioception from lower limb/trunk.\n\nVentral spinocerebellar tract (VSCT): originates in spinal gray matter, most fibers cross then recross in cerebellum, enters via superior cerebellar peduncle. Both provide unconscious proprioception for motor coordination.`,
    clinical_significance: 'Friedreich ataxia affects dorsal spinocerebellar tract (plus dorsal columns, lateral corticospinal). Loss causes ataxia, sensory deficits. Spinocerebellar ataxias (SCAs). Typically tested indirectly via cerebellar examination.',
    origin: 'Clarke\'s nucleus (DSCT), spinal gray matter (VSCT)',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior and anterior spinal arteries',
    model_reference: 'spinocerebellar_tracts',
    image_references: [],
    difficulty_rating: 5,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // MENINGES
  // ==========================================================================
  {
    canonical_name: 'Dura Mater',
    common_names: ['Pachymeninx', 'Tough mother'],
    latin_name: 'Dura mater',
    pronunciation_ipa: '/ˈdʊrə ˈmeɪtər/',
    structure_type: StructureType.FASCIA,
    parent_structure_id: null,
    definition_brief: 'Outermost thick fibrous meningeal layer lining skull and vertebral canal.',
    description_full: `Thick, tough outermost meningeal layer. In cranium, consists of two layers: periosteal (outer, adheres to skull) and meningeal (inner). Layers separate to form dural venous sinuses.\n\nForms falx cerebri (between hemispheres), tentorium cerebelli (over cerebellum), falx cerebelli, diaphragma sellae. Spinal dura is single layer separated from vertebrae by epidural space.`,
    clinical_significance: 'Epidural hematoma between skull and dura (middle meningeal artery injury). Subdural hematoma between dura and arachnoid (bridging vein injury). Dural AV fistulas. Dural venous sinus thrombosis. Spinal epidural abscess/hematoma.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Trigeminal nerve (CN V), cervical nerves (C1-C3), vagus nerve (CN X)',
    blood_supply: 'Middle meningeal artery (primary), others',
    model_reference: 'dura_mater',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Arachnoid Mater',
    common_names: ['Arachnoid', 'Spider mother'],
    latin_name: 'Arachnoidea mater',
    pronunciation_ipa: '/əˈræknɔɪd ˈmeɪtər/',
    structure_type: StructureType.FASCIA,
    parent_structure_id: null,
    definition_brief: 'Middle meningeal layer forming outer boundary of subarachnoid space containing CSF.',
    description_full: `Avascular membrane deep to dura, separated by subdural space (potential space). Arachnoid trabeculae extend through subarachnoid space to pia mater, creating web-like appearance.\n\nSubarachnoid space contains CSF, cerebral arteries/veins. Arachnoid granulations project into dural venous sinuses (especially superior sagittal sinus) for CSF absorption.`,
    clinical_significance: 'Subarachnoid hemorrhage (blood in subarachnoid space, typically from aneurysm rupture). Meningitis causes inflammation. Arachnoid cysts are benign CSF collections. Lumbar puncture enters subarachnoid space. Arachnoiditis causes chronic pain.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'arachnoid_mater',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Pia Mater',
    common_names: ['Tender mother'],
    latin_name: 'Pia mater',
    pronunciation_ipa: '/ˈpaɪə ˈmeɪtər/',
    structure_type: StructureType.FASCIA,
    parent_structure_id: null,
    definition_brief: 'Innermost delicate meningeal layer adherent to brain and spinal cord surface.',
    description_full: `Thin, delicate innermost layer intimately adhering to brain/spinal cord surface, following all gyri and sulci. Highly vascular, carrying blood vessels onto neural surface.\n\nIn spinal cord, forms denticulate ligaments (lateral extensions anchoring cord). Together with arachnoid forms leptomeninges. Fuses with ependymal lining of ventricles to form choroid plexus.`,
    clinical_significance: 'Rarely injured in isolation. Involved in meningitis (leptomeningitis). Pial arteriovenous malformations. Thickening in chronic inflammation. Subarachnoid hemorrhage tracks along pia surface.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Branches of cerebral and spinal arteries',
    model_reference: 'pia_mater',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // CEREBRAL VASCULATURE - Circle of Willis
  // ==========================================================================
  {
    canonical_name: 'Circle of Willis',
    common_names: ['Circulus arteriosus cerebri', 'Cerebral arterial circle'],
    latin_name: 'Circulus arteriosus cerebri',
    pronunciation_ipa: '/ˈsɜːrkəl əv ˈwɪlɪs/',
    structure_type: StructureType.ARTERY,
    parent_structure_id: null,
    definition_brief: 'Arterial anastomotic ring at base of brain providing collateral circulation.',
    description_full: `Hexagonal arterial ring at skull base surrounding optic chiasm and pituitary stalk. Connects anterior (carotid) and posterior (vertebrobasilar) circulations.\n\nComponents: anterior cerebral arteries (ACA), anterior communicating artery (ACoA), internal carotid arteries (ICA), posterior communicating arteries (PCoA), posterior cerebral arteries (PCA). Variations common (complete circle in ~50% of people).`,
    clinical_significance: 'Provides collateral blood flow if one vessel is occluded. Common site of saccular aneurysms (ACoA most common, then PCoA). Incomplete circle increases stroke risk. Aneurysm rupture causes subarachnoid hemorrhage.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'circle_of_willis',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Middle Cerebral Artery',
    common_names: ['MCA'],
    latin_name: 'Arteria cerebri media',
    pronunciation_ipa: '/ˈmɪdəl səˈriːbrəl ˈɑːrtəri/',
    structure_type: StructureType.ARTERY,
    parent_structure_id: null,
    definition_brief: 'Largest cerebral artery supplying lateral cerebral hemisphere and deep structures.',
    description_full: `Direct continuation of internal carotid artery, largest terminal branch. Courses laterally in lateral sulcus. Divides into M1 (horizontal, gives lenticulostriate arteries), M2 (insular), M3 (opercular), M4 (cortical).\n\nSupplies: lateral frontal/parietal/temporal lobes, basal ganglia (lenticulostriate), internal capsule. Most common site of ischemic stroke.`,
    clinical_significance: 'MCA stroke most common. Left MCA: aphasia, right hemiplegia/hemisensory loss. Right MCA: neglect, left hemiplegia. Superior division: face/arm > leg weakness. Inferior division: Wernicke\'s aphasia. Lenticulostriate infarcts: pure motor hemiparesis.',
    origin: 'Internal carotid artery',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'middle_cerebral_artery',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Anterior Cerebral Artery',
    common_names: ['ACA'],
    latin_name: 'Arteria cerebri anterior',
    pronunciation_ipa: '/ænˈtɪriər səˈriːbrəl ˈɑːrtəri/',
    structure_type: StructureType.ARTERY,
    parent_structure_id: null,
    definition_brief: 'Cerebral artery supplying medial hemisphere including motor/sensory cortex for leg.',
    description_full: `Smaller terminal branch of internal carotid. Courses anteromedially above optic nerve, connected to contralateral ACA by anterior communicating artery. A1 segment: ICA to ACoA. A2: vertical, curves around corpus callosum.\n\nSupplies: medial frontal/parietal lobes, corpus callosum, anterior internal capsule. Includes leg area of motor/sensory cortex (paracentral lobule).`,
    clinical_significance: 'ACA stroke less common than MCA. Causes contralateral leg weakness/sensory loss > arm/face. Can cause akinetic mutism (bilateral), transcortical motor aphasia. Anterior communicating artery aneurysms most common overall.',
    origin: 'Internal carotid artery',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'anterior_cerebral_artery',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Posterior Cerebral Artery',
    common_names: ['PCA'],
    latin_name: 'Arteria cerebri posterior',
    pronunciation_ipa: '/pɒˈstɪriər səˈriːbrəl ˈɑːrtəri/',
    structure_type: StructureType.ARTERY,
    parent_structure_id: null,
    definition_brief: 'Terminal branch of basilar artery supplying occipital lobe, medial temporal lobe, and thalamus.',
    description_full: `Terminal branch of basilar artery. P1 segment: basilar to posterior communicating artery. P2: wraps around midbrain. P3/P4: supply occipital/temporal cortex.\n\nSupplies: occipital lobe (visual cortex), medial temporal lobe (hippocampus), midbrain, thalamus (via perforators), posterior limb internal capsule. Gives thalamoperforators, thalamogeniculate arteries.`,
    clinical_significance: 'PCA stroke causes contralateral homonymous hemianopia (often with macular sparing). Bilateral PCA: cortical blindness, Anton syndrome. Can cause thalamic pain syndrome, memory deficits (hippocampus), alexia without agraphia (left PCA + splenium).',
    origin: 'Basilar artery',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'posterior_cerebral_artery',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Basilar Artery',
    common_names: [],
    latin_name: 'Arteria basilaris',
    pronunciation_ipa: '/ˈbæzɪlər ˈɑːrtəri/',
    structure_type: StructureType.ARTERY,
    parent_structure_id: null,
    definition_brief: 'Unpaired artery formed by vertebral arteries, supplying brainstem and cerebellum.',
    description_full: `Formed at pontomedullary junction by confluence of vertebral arteries. Ascends in basilar sulcus of pons. Terminates by bifurcating into posterior cerebral arteries.\n\nBranches: anterior inferior cerebellar artery (AICA), pontine perforators, superior cerebellar artery (SCA), posterior cerebral arteries. Supplies pons, midbrain, cerebellum, occipital lobes.`,
    clinical_significance: 'Basilar artery occlusion causes locked-in syndrome (bilateral ventral pons infarction), coma, death. Top of basilar syndrome: visual/oculomotor disturbances, behavioral changes. Basilar artery aneurysm rare but serious. Atherosclerosis common.',
    origin: 'Confluence of vertebral arteries',
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: null,
    model_reference: 'basilar_artery',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // CRANIAL NERVE NUCLEI (Selected)
  // ==========================================================================
  {
    canonical_name: 'Oculomotor Nucleus',
    common_names: ['CN III nucleus'],
    latin_name: 'Nucleus nervi oculomotorii',
    pronunciation_ipa: '/ˌɒkjʊloʊˈmoʊtər ˈnuːkliəs/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Midbrain motor nucleus of cranial nerve III controlling eye movements and pupil constriction.',
    description_full: `Located in periaqueductal gray at level of superior colliculus. Contains somatic motor neurons (for extraocular muscles) and Edinger-Westphal nucleus (parasympathetic, for pupil constriction/accommodation).\n\nSupplies: medial rectus, superior rectus, inferior rectus, inferior oblique, levator palpebrae superioris. Parasympathetic fibers control pupillary sphincter and ciliary muscle.`,
    clinical_significance: 'Lesions cause ipsilateral ptosis, "down and out" eye position, dilated pupil, impaired accommodation. Weber syndrome: CN III palsy + contralateral hemiplegia (midbrain stroke). Compressive lesions (aneurysm, uncal herniation) affect pupil. Diabetic CN III palsy spares pupil.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery, basilar artery perforators',
    model_reference: 'oculomotor_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Facial Nucleus',
    common_names: ['CN VII motor nucleus'],
    latin_name: 'Nucleus nervi facialis',
    pronunciation_ipa: '/ˈfeɪʃəl ˈnuːkliəs/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Pontine motor nucleus of cranial nerve VII controlling facial expression muscles.',
    description_full: `Located in ventrolateral pontine tegmentum. Lower motor neurons innervating facial expression muscles. Nerve fibers loop around abducens nucleus (internal genu) before exiting brainstem.\n\nUpper face receives bilateral cortical input; lower face receives contralateral input only. This explains different patterns in central vs peripheral facial palsy.`,
    clinical_significance: 'Upper motor neuron lesion (stroke): contralateral lower face weakness, forehead spared. Lower motor neuron lesion (Bell\'s palsy, brainstem lesion): ipsilateral complete facial paralysis including forehead. Millard-Gubler syndrome: CN VI + VII + contralateral hemiplegia.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Basilar artery perforators',
    model_reference: 'facial_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Hypoglossal Nucleus',
    common_names: ['CN XII nucleus'],
    latin_name: 'Nucleus nervi hypoglossi',
    pronunciation_ipa: '/ˌhaɪpoʊˈɡlɒsəl ˈnuːkliəs/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Medullary motor nucleus of cranial nerve XII controlling tongue movements.',
    description_full: `Column of motor neurons in dorsal medulla, beneath floor of fourth ventricle (hypoglossal trigone). Lower motor neurons innervating intrinsic and extrinsic tongue muscles.\n\nReceives bilateral cortical input (upper motor neurons). Nerve exits between pyramid and olive, courses to tongue.`,
    clinical_significance: 'Lower motor neuron lesion: ipsilateral tongue atrophy, fasciculations, deviation toward lesion side on protrusion. Upper motor neuron lesion: contralateral deviation without atrophy. Medial medullary syndrome: CN XII palsy + contralateral hemiplegia + proprioception loss.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior spinal artery',
    model_reference: 'hypoglossal_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // WHITE MATTER TRACTS & COMMISSURES
  // ==========================================================================
  {
    canonical_name: 'Corpus Callosum',
    common_names: ['Great commissure'],
    latin_name: 'Corpus callosum',
    pronunciation_ipa: '/ˈkɔːrpəs kəˈloʊsəm/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'Largest white matter commissure connecting left and right cerebral hemispheres.',
    description_full: `Massive bundle of ~200 million nerve fibers connecting corresponding cortical areas between hemispheres. Divided into rostrum, genu, body, and splenium (posterior, thickest part).\n\nGenu connects frontal lobes, body connects motor/sensory areas, splenium connects parietal/occipital/temporal lobes. Critical for interhemispheric communication and coordination.`,
    clinical_significance: 'Agenesis of corpus callosum (congenital) causes developmental delays, seizures. Surgical callosotomy for intractable epilepsy produces split-brain syndrome. Infarction (usually splenium) causes alexia without agraphia. Multiple sclerosis commonly affects corpus callosum.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Anterior cerebral artery (pericallosal artery), posterior cerebral artery',
    model_reference: 'corpus_callosum',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Internal Capsule',
    common_names: [],
    latin_name: 'Capsula interna',
    pronunciation_ipa: '/ɪnˈtɜːrnəl ˈkæpsjuːl/',
    structure_type: StructureType.NERVE,
    parent_structure_id: null,
    definition_brief: 'White matter structure carrying ascending and descending fibers between cortex and subcortical structures.',
    description_full: `V-shaped white matter bundle between thalamus (medial) and lentiform nucleus (lateral). Divided into anterior limb, genu, and posterior limb. Contains thalamocortical and corticofugal fibers.\n\nAnterior limb: frontopontine fibers, anterior thalamic radiations. Genu: corticobulbar fibers. Posterior limb: corticospinal fibers (motor), thalamocortical fibers (sensory), corticorubral, corticopontine.`,
    clinical_significance: 'Lacunar stroke (lenticulostriate arteries) causes pure motor hemiparesis (posterior limb), pure sensory stroke (thalamus/posterior limb). Larger strokes cause dense hemiplegia, hemisensory loss, hemianopia. Small lesion causes large deficit due to fiber concentration.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Lateral striate arteries (lenticulostriate, from MCA), anterior choroidal artery',
    model_reference: 'internal_capsule',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },

  // ==========================================================================
  // ADDITIONAL STRUCTURES (to reach 60+)
  // ==========================================================================
  {
    canonical_name: 'Insular Cortex',
    common_names: ['Insula', 'Island of Reil'],
    latin_name: 'Lobus insularis',
    pronunciation_ipa: '/ˈɪnsjʊlər ˈkɔːrtɛks/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Hidden cortex deep to lateral sulcus involved in interoception, emotion, and autonomic control.',
    description_full: `Located deep within lateral sulcus, covered by frontal, parietal, and temporal opercula. Divided into anterior (agranular) and posterior (granular) portions by central sulcus of insula.\n\nInvolved in taste, visceral sensation, interoception, emotion, empathy, autonomic control. Anterior insula processes subjective feelings, posterior insula represents objective bodily states.`,
    clinical_significance: 'Insular stroke can cause pain syndromes, autonomic dysfunction, aphasia (if dominant hemisphere). Rarely damaged in isolation. Involved in addiction, anxiety disorders. Stimulation produces visceral sensations, taste, autonomic responses.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Middle cerebral artery (insular branches)',
    model_reference: 'insular_cortex',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Pineal Gland',
    common_names: ['Pineal body', 'Epiphysis cerebri'],
    latin_name: 'Glandula pinealis',
    pronunciation_ipa: '/ˈpɪniəl ɡlænd/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Small endocrine gland in epithalamus producing melatonin and regulating circadian rhythms.',
    description_full: `Small (~8mm) midline structure attached to posterior third ventricle roof. Shaped like pine cone. Contains pinealocytes (produce melatonin) and glial cells. Calcifies with age (visible on imaging).\n\nReceives sympathetic input from superior cervical ganglion via nervi conarii. Melatonin secretion regulated by light/dark cycle via retinohypothalamic tract.`,
    clinical_significance: 'Pineal tumors (pineoblastoma, germinoma) compress tectum causing Parinaud syndrome (upgaze palsy, convergence-retraction nystagmus). Calcification normal after puberty. Precocious puberty with pineal destruction. Seasonal affective disorder linked to melatonin dysfunction.',
    origin: null,
    insertion: null,
    action: null,
    innervation: 'Sympathetic fibers from superior cervical ganglion',
    blood_supply: 'Posterior cerebral artery, superior cerebellar artery',
    model_reference: 'pineal_gland',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Pituitary Gland',
    common_names: ['Hypophysis', 'Hypophysis cerebri'],
    latin_name: 'Hypophysis',
    pronunciation_ipa: '/pɪˈtuːɪtəri ɡlænd/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Master endocrine gland in sella turcica, consisting of anterior and posterior lobes.',
    description_full: `Located in sella turcica of sphenoid bone. Consists of adenohypophysis (anterior lobe, produces ACTH, TSH, GH, prolactin, FSH, LH) and neurohypophysis (posterior lobe, releases ADH and oxytocin from hypothalamus).\n\nConnected to hypothalamus via infundibulum (pituitary stalk). Hypothalamic-pituitary portal system carries releasing/inhibiting hormones to anterior pituitary.`,
    clinical_significance: 'Pituitary adenomas cause hormone excess (acromegaly, Cushing\'s, prolactinoma) or mass effect (bitemporal hemianopia from optic chiasm compression, hypopituitarism). Pituitary apoplexy (hemorrhage/infarction). Sheehan syndrome (postpartum necrosis). Diabetes insipidus (posterior pituitary).',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Superior and inferior hypophyseal arteries (from internal carotid)',
    model_reference: 'pituitary_gland',
    image_references: [],
    difficulty_rating: 3,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Mammillary Bodies',
    common_names: ['Corpora mammillaria'],
    latin_name: 'Corpora mammillaria',
    pronunciation_ipa: '/ˈmæmɪləri ˈbɒdiz/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Paired hypothalamic nuclei visible on ventral brain surface, involved in memory circuitry.',
    description_full: `Small paired rounded structures on ventral hypothalamus, posterior to pituitary. Part of Papez circuit: receive input from hippocampus via fornix, project to anterior thalamus via mammillothalamic tract.\n\nCritical node in limbic system memory circuits. Also project to tegmentum via mammillotegmental tract. Atrophy visible on MRI.`,
    clinical_significance: 'Damaged in Wernicke-Korsakoff syndrome (thiamine deficiency, chronic alcoholism) causing amnesia, confabulation. Part of Papez circuit; bilateral damage impairs memory. Atrophy in Alzheimer\'s disease, chronic alcohol use.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery, posterior communicating artery',
    model_reference: 'mammillary_bodies',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Red Nucleus',
    common_names: ['Nucleus ruber'],
    latin_name: 'Nucleus ruber',
    pronunciation_ipa: '/rɛd ˈnuːkliəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Midbrain tegmental nucleus involved in motor coordination, appearing pinkish on fresh specimens.',
    description_full: `Located in midbrain tegmentum at level of superior colliculus. Reddish color due to iron content and vascularity. Divided into parvocellular (rostral) and magnocellular (caudal) portions.\n\nReceives input from cerebellum (dentate nucleus) and motor cortex. Magnocellular portion gives rise to rubrospinal tract (descends to spinal cord). Parvocellular portion projects to inferior olive.`,
    clinical_significance: 'Lesions rare in isolation. Part of circuits affected in Benedikt syndrome (midbrain stroke): CN III palsy + contralateral ataxia/tremor. Involved in Holmes tremor (rubral tremor). Part of Guillain-Mollaret triangle (red nucleus-olive-cerebellum).',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery, superior cerebellar artery',
    model_reference: 'red_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Inferior Olivary Nucleus',
    common_names: ['Inferior olive', 'Olive'],
    latin_name: 'Nucleus olivaris inferior',
    pronunciation_ipa: '/ɪnˈfɪriər ˌɒlɪˈvɛri ˈnuːkliəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Medullary nucleus forming olive prominence, projecting climbing fibers to cerebellum.',
    description_full: `Located in ventrolateral medulla, creates olive prominence on external surface. Distinctive convoluted gray matter structure resembling bag. Part of Guillain-Mollaret triangle with red nucleus and cerebellum.\n\nProjects climbing fibers to contralateral cerebellar cortex via inferior cerebellar peduncle. Critical for motor learning, timing. Receives input from red nucleus, spinal cord.`,
    clinical_significance: 'Hypertrophic olivary degeneration occurs after lesions in Guillain-Mollaret triangle (red nucleus or dentate nucleus). Causes palatal tremor (palatal myoclonus). Visible as T2 hyperintensity on MRI.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Vertebral artery, posterior inferior cerebellar artery (PICA)',
    model_reference: 'inferior_olivary_nucleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Periaqueductal Gray',
    common_names: ['PAG', 'Central gray'],
    latin_name: 'Substantia grisea centralis',
    pronunciation_ipa: '/ˌpɛriəˈkwɛdʌktəl ɡreɪ/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Gray matter surrounding cerebral aqueduct, involved in pain modulation and autonomic control.',
    description_full: `Gray matter surrounding cerebral aqueduct in midbrain. Organized into longitudinal columns with distinct functions: ventromedial (freezing, quiescence), lateral (fight-or-flight), dorsal (alertness).\n\nCritical for descending pain modulation (projects to raphe nuclei, which project to dorsal horn). Also involved in defensive behaviors, vocalization, reproductive behavior, autonomic control.`,
    clinical_significance: 'Stimulation produces analgesia (endogenous opioid release). Lesions cause loss of conscious state. Involved in panic disorder, anxiety. Target for deep brain stimulation in chronic pain. Pineal tumors can invade PAG.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Posterior cerebral artery, superior cerebellar artery',
    model_reference: 'periaqueductal_gray',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
  {
    canonical_name: 'Locus Coeruleus',
    common_names: ['Blue spot'],
    latin_name: 'Locus caeruleus',
    pronunciation_ipa: '/ˈloʊkəs sɪˈruːliəs/',
    structure_type: StructureType.ORGAN,
    parent_structure_id: null,
    definition_brief: 'Pontine noradrenergic nucleus appearing bluish, involved in arousal and stress response.',
    description_full: `Small nucleus in dorsal pontine tegmentum near floor of fourth ventricle. Contains ~15,000 noradrenergic neurons (in humans) with widespread projections to entire CNS.\n\nBlue appearance due to neuromelanin pigment. Projects to cortex, cerebellum, spinal cord, affecting arousal, attention, stress response, sleep-wake cycles. Most widespread projection system in brain.`,
    clinical_significance: 'Degeneration in Parkinson\'s disease, Alzheimer\'s disease. Involved in PTSD, anxiety disorders, panic attacks. Hyperactivity in opiate withdrawal. Affected by alpha-2 agonists (clonidine, dexmedetomidine). Involved in REM sleep regulation.',
    origin: null,
    insertion: null,
    action: null,
    innervation: null,
    blood_supply: 'Basilar artery perforators',
    model_reference: 'locus_coeruleus',
    image_references: [],
    difficulty_rating: 4,
    prerequisite_ids: [],
  },
];

// ============================================================================
// Relationships (Minimum 80)
// ============================================================================

export const neuroanatomyRelationships: Omit<Relationship, 'id' | 'source_structure_id' | 'target_structure_id'>[] = [
  // Tract pathways
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Lateral corticospinal tract originates from pyramidal cells in precentral gyrus',
    bidirectional: false,
    clinical_relevance: 'Precentral gyrus lesions cause upper motor neuron signs; tract lesions in spinal cord cause similar deficits below level of lesion',
  },
  {
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Lateral corticospinal tract descends through internal capsule (posterior limb)',
    bidirectional: false,
    clinical_relevance: 'Internal capsule stroke commonly affects corticospinal tract causing dense hemiplegia',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Spinothalamic tract terminates in VPL nucleus of thalamus',
    bidirectional: false,
    clinical_relevance: 'Thalamic lesions can cause loss of pain/temperature sensation contralaterally',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Dorsal column pathway synapses in VPL thalamus before projecting to postcentral gyrus',
    bidirectional: false,
    clinical_relevance: 'Complete pathway required for proprioception and fine touch discrimination',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Spinocerebellar tracts enter cerebellum via inferior and superior cerebellar peduncles',
    bidirectional: false,
    clinical_relevance: 'Cerebellar lesions affect proprioceptive feedback causing ataxia',
  },

  // Vascular territories
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Frontal lobe lateral surface supplied by middle cerebral artery',
    bidirectional: false,
    clinical_relevance: 'MCA stroke affects motor/speech areas causing hemiparesis and aphasia',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Frontal lobe medial surface supplied by anterior cerebral artery',
    bidirectional: false,
    clinical_relevance: 'ACA stroke preferentially affects leg motor/sensory function',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Occipital lobe supplied by posterior cerebral artery',
    bidirectional: false,
    clinical_relevance: 'PCA stroke causes homonymous hemianopia',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Basal ganglia supplied by lateral striate arteries (lenticulostriate branches)',
    bidirectional: false,
    clinical_relevance: 'Hypertensive hemorrhage commonly occurs in basal ganglia (putamen)',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Internal capsule supplied by lateral striate arteries and anterior choroidal artery',
    bidirectional: false,
    clinical_relevance: 'Lacunar infarcts in internal capsule cause pure motor hemiparesis',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Thalamus supplied by posterior cerebral artery and posterior communicating artery',
    bidirectional: false,
    clinical_relevance: 'Thalamic stroke causes sensory loss and potential thalamic pain syndrome',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Midbrain supplied by posterior cerebral artery and superior cerebellar artery',
    bidirectional: false,
    clinical_relevance: 'Midbrain stroke causes cranial nerve III palsy and various crossed syndromes',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Pons supplied by basilar artery and branches',
    bidirectional: false,
    clinical_relevance: 'Pontine stroke can cause locked-in syndrome',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Medulla supplied by vertebral artery and PICA',
    bidirectional: false,
    clinical_relevance: 'Lateral medullary syndrome (Wallenberg) from PICA occlusion',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Cerebellum supplied by PICA, AICA, and SCA',
    bidirectional: false,
    clinical_relevance: 'Cerebellar stroke causes ataxia, nystagmus, dysmetria',
  },
  {
    relationship_type: RelationshipType.SUPPLIED_BY,
    description: 'Spinal cord anterior 2/3 supplied by anterior spinal artery',
    bidirectional: false,
    clinical_relevance: 'Anterior spinal artery syndrome spares dorsal columns',
  },
  {
    relationship_type: RelationshipType.BRANCH_OF,
    description: 'Middle cerebral artery branches from internal carotid artery',
    bidirectional: false,
    clinical_relevance: 'ICA occlusion can affect entire MCA territory',
  },
  {
    relationship_type: RelationshipType.BRANCH_OF,
    description: 'Anterior cerebral artery branches from internal carotid artery',
    bidirectional: false,
    clinical_relevance: 'ICA dissection can affect both ACA and MCA',
  },
  {
    relationship_type: RelationshipType.BRANCH_OF,
    description: 'Posterior cerebral artery branches from basilar artery',
    bidirectional: false,
    clinical_relevance: 'Top of basilar syndrome affects both PCAs',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Basilar artery formed from confluence of vertebral arteries',
    bidirectional: false,
    clinical_relevance: 'Vertebral artery dissection can lead to basilar thrombosis',
  },

  // Functional connections - Motor system
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Precentral gyrus projects to striatum (caudate and putamen)',
    bidirectional: false,
    clinical_relevance: 'Cortical-striatal pathway critical for movement initiation',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Striatum (caudate and putamen) projects to globus pallidus',
    bidirectional: false,
    clinical_relevance: 'Part of direct and indirect basal ganglia pathways',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Globus pallidus internal segment projects to thalamus (VL/VA)',
    bidirectional: false,
    clinical_relevance: 'Major output of basal ganglia, regulates thalamic activity',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Thalamus VL/VA projects to motor cortex (precentral gyrus)',
    bidirectional: false,
    clinical_relevance: 'Completes motor loop; thalamic stroke affects movement',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Substantia nigra pars compacta projects to striatum (nigrostriatal pathway)',
    bidirectional: false,
    clinical_relevance: 'Degeneration of this pathway causes Parkinson\'s disease',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Subthalamic nucleus projects to globus pallidus internal segment',
    bidirectional: false,
    clinical_relevance: 'Provides excitatory drive; lesions cause hemiballismus',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Globus pallidus external segment projects to subthalamic nucleus',
    bidirectional: false,
    clinical_relevance: 'Part of indirect pathway regulating movement',
  },

  // Functional connections - Sensory system
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Thalamus VPL/VPM projects to postcentral gyrus',
    bidirectional: false,
    clinical_relevance: 'Final relay for somatosensory information to cortex',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Lateral geniculate nucleus (thalamus) projects to occipital lobe visual cortex',
    bidirectional: false,
    clinical_relevance: 'Lesions anywhere in pathway cause visual field defects',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Medial geniculate nucleus (thalamus) projects to temporal lobe auditory cortex',
    bidirectional: false,
    clinical_relevance: 'Relay for auditory information',
  },

  // Limbic system connections
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Hippocampus projects to mammillary bodies via fornix',
    bidirectional: false,
    clinical_relevance: 'Part of Papez circuit; damage causes memory impairment',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Mammillary bodies project to anterior thalamus via mammillothalamic tract',
    bidirectional: false,
    clinical_relevance: 'Wernicke-Korsakoff syndrome affects this pathway',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Anterior thalamus projects to cingulate gyrus',
    bidirectional: false,
    clinical_relevance: 'Part of Papez circuit for emotion and memory',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Cingulate gyrus connects to hippocampus (completes Papez circuit)',
    bidirectional: false,
    clinical_relevance: 'Circuit disruption impairs memory consolidation',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Amygdala projects to hypothalamus',
    bidirectional: false,
    clinical_relevance: 'Emotional responses trigger autonomic/endocrine changes',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Amygdala has reciprocal connections with hippocampus',
    bidirectional: true,
    clinical_relevance: 'Emotional enhancement of memory formation',
  },

  // Cerebellar connections
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Dentate nucleus projects to thalamus VL via superior cerebellar peduncle',
    bidirectional: false,
    clinical_relevance: 'Cerebellar output to motor cortex for coordination',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Dentate nucleus projects to red nucleus',
    bidirectional: false,
    clinical_relevance: 'Part of Guillain-Mollaret triangle',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Red nucleus projects to inferior olivary nucleus',
    bidirectional: false,
    clinical_relevance: 'Guillain-Mollaret triangle; lesions cause palatal tremor',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Inferior olivary nucleus projects climbing fibers to cerebellum',
    bidirectional: false,
    clinical_relevance: 'Critical for motor learning and timing',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Cerebellum receives input from pons via middle cerebellar peduncle',
    bidirectional: false,
    clinical_relevance: 'Corticopontocerebellar pathway for motor planning',
  },

  // Brainstem connections
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Midbrain continuous with pons',
    bidirectional: true,
    clinical_relevance: 'Lesions can affect both structures',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Pons continuous with medulla',
    bidirectional: true,
    clinical_relevance: 'Brainstem continuity; pontine and medullary syndromes can overlap',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Medulla continuous with spinal cord at foramen magnum',
    bidirectional: true,
    clinical_relevance: 'Junction site for Chiari malformations',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Midbrain contains oculomotor nucleus (CN III)',
    bidirectional: false,
    clinical_relevance: 'Midbrain lesions cause CN III palsies',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Pons contains facial nucleus (CN VII)',
    bidirectional: false,
    clinical_relevance: 'Pontine lesions cause facial paralysis',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Medulla contains hypoglossal nucleus (CN XII)',
    bidirectional: false,
    clinical_relevance: 'Medullary lesions cause tongue deviation',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Midbrain contains substantia nigra',
    bidirectional: false,
    clinical_relevance: 'Parkinson\'s disease affects midbrain substantia nigra',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Pons contains locus coeruleus',
    bidirectional: false,
    clinical_relevance: 'Noradrenergic system affected in stress/anxiety',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Medulla contains inferior olivary nucleus',
    bidirectional: false,
    clinical_relevance: 'Hypertrophic olivary degeneration visible on MRI',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Midbrain contains periaqueductal gray',
    bidirectional: false,
    clinical_relevance: 'Pain modulation and defensive behaviors',
  },

  // Ventricular connections
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Lateral ventricles communicate with third ventricle via foramina of Monro',
    bidirectional: true,
    clinical_relevance: 'Colloid cysts at foramen cause acute hydrocephalus',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Third ventricle connects to fourth ventricle via cerebral aqueduct',
    bidirectional: true,
    clinical_relevance: 'Aqueductal stenosis causes obstructive hydrocephalus',
  },
  {
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'CSF flows from fourth ventricle to subarachnoid space via foramina of Luschka and Magendie',
    bidirectional: false,
    clinical_relevance: 'Obstruction causes communicating hydrocephalus',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Lateral ventricles contain choroid plexus producing CSF',
    bidirectional: false,
    clinical_relevance: 'Choroid plexus papilloma causes excess CSF production',
  },
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Fourth ventricle contains choroid plexus',
    bidirectional: false,
    clinical_relevance: 'Primary CSF production site',
  },

  // White matter connections
  {
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Corpus callosum connects left and right hemispheres',
    bidirectional: true,
    clinical_relevance: 'Callosotomy for epilepsy causes split-brain syndrome',
  },
  {
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Internal capsule carries corticospinal tract from cortex to brainstem',
    bidirectional: false,
    clinical_relevance: 'Small capsular stroke causes large deficit',
  },
  {
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Internal capsule carries thalamocortical radiations from thalamus to cortex',
    bidirectional: false,
    clinical_relevance: 'Capsular stroke affects both motor and sensory functions',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Fornix connects hippocampus to septal nuclei and mammillary bodies',
    bidirectional: false,
    clinical_relevance: 'Fornix damage causes amnesia',
  },

  // Meningeal relationships
  {
    relationship_type: RelationshipType.SUPERFICIAL_TO,
    description: 'Dura mater superficial to arachnoid mater',
    bidirectional: false,
    clinical_relevance: 'Subdural space between dura and arachnoid',
  },
  {
    relationship_type: RelationshipType.SUPERFICIAL_TO,
    description: 'Arachnoid mater superficial to pia mater',
    bidirectional: false,
    clinical_relevance: 'Subarachnoid space contains CSF and vessels',
  },
  {
    relationship_type: RelationshipType.DEEP_TO,
    description: 'Pia mater adheres directly to brain surface',
    bidirectional: false,
    clinical_relevance: 'Pia carries blood vessels into brain parenchyma',
  },

  // Circle of Willis relationships
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Internal carotid artery gives rise to middle cerebral artery',
    bidirectional: false,
    clinical_relevance: 'ICA occlusion affects MCA territory',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Internal carotid artery gives rise to anterior cerebral artery',
    bidirectional: false,
    clinical_relevance: 'ICA terminus occlusion affects both territories',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Anterior cerebral arteries connected by anterior communicating artery',
    bidirectional: true,
    clinical_relevance: 'Provides collateral flow; common aneurysm site',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Posterior communicating artery connects ICA to posterior cerebral artery',
    bidirectional: true,
    clinical_relevance: 'Connects anterior and posterior circulations; aneurysm causes CN III palsy',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Basilar artery terminates into posterior cerebral arteries',
    bidirectional: false,
    clinical_relevance: 'Top of basilar syndrome affects bilateral PCAs',
  },

  // Additional motor/sensory correlations
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Precentral gyrus (motor) adjacent to postcentral gyrus (sensory) across central sulcus',
    bidirectional: false,
    clinical_relevance: 'Stroke can affect both motor and sensory functions',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Frontal lobe separated from parietal lobe by central sulcus',
    bidirectional: false,
    clinical_relevance: 'Key landmark for localization',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Parietal lobe separated from occipital lobe by parieto-occipital sulcus',
    bidirectional: false,
    clinical_relevance: 'Posterior cerebral artery territory boundary',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Temporal lobe separated from frontal/parietal lobes by lateral sulcus',
    bidirectional: false,
    clinical_relevance: 'MCA courses in lateral sulcus',
  },

  // Hypothalamic-pituitary connections
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Hypothalamus connected to pituitary gland via infundibulum',
    bidirectional: false,
    clinical_relevance: 'Hypothalamic-pituitary axis controls endocrine function',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Supraoptic and paraventricular nuclei project to posterior pituitary',
    bidirectional: false,
    clinical_relevance: 'ADH and oxytocin released from posterior pituitary',
  },

  // Additional tract relationships
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Red nucleus gives rise to rubrospinal tract',
    bidirectional: false,
    clinical_relevance: 'Facilitates flexor tone; lesions cause extension posturing',
  },
  {
    relationship_type: RelationshipType.PASSES_THROUGH,
    description: 'Optic radiations pass through internal capsule and deep white matter to occipital lobe',
    bidirectional: false,
    clinical_relevance: 'Meyer\'s loop lesions cause "pie in the sky" visual field defects',
  },

  // Add 5 more to reach 80+
  {
    relationship_type: RelationshipType.CONTAINS,
    description: 'Insular cortex hidden beneath frontal, parietal, and temporal opercula',
    bidirectional: false,
    clinical_relevance: 'MCA strokes can affect insular cortex causing pain syndromes',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Pineal gland attached to posterior third ventricle roof',
    bidirectional: false,
    clinical_relevance: 'Pineal tumors compress tectum and cerebral aqueduct',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Pituitary gland sits in sella turcica, inferior to optic chiasm',
    bidirectional: false,
    clinical_relevance: 'Pituitary adenomas compress optic chiasm causing bitemporal hemianopia',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Periaqueductal gray surrounds cerebral aqueduct in midbrain',
    bidirectional: false,
    clinical_relevance: 'Involved in pain modulation and defensive behaviors',
  },
  {
    relationship_type: RelationshipType.CONTINUOUS_WITH,
    description: 'Locus coeruleus located in dorsal pons near fourth ventricle',
    bidirectional: false,
    clinical_relevance: 'Noradrenergic projections affect arousal and stress response',
  },
];

// ============================================================================
// Export complete seed data
// ============================================================================

export interface NeuroanatomySeedData {
  region: Omit<Region, 'id'>;
  systems: Omit<System, 'id'>[];
  structures: Omit<Structure, 'id' | 'region_id' | 'system_ids' | 'created_at' | 'updated_at'>[];
  relationships: Omit<Relationship, 'id' | 'source_structure_id' | 'target_structure_id'>[];
}

export const neuroanatomySeedData: NeuroanatomySeedData = {
  region: neuroanatomyRegion,
  systems: neuroanatomySystems,
  structures: neuroanatomyStructures,
  relationships: neuroanatomyRelationships,
};
